from app.services.listening_content.base import scenario

CATEGORY = "Food & drink"

FOOD_SCENARIOS = [
    scenario(
        "convenience-store",
        "At the convenience store",
        "Heat up a bento, skip the bag, find the ATM, and buy stamps for a postcard home.",
        setting="Konbini",
        category=CATEGORY,
        level="Beginner",
        lines=[
            ("Clerk", "いらっしゃいませ。", "Irasshaimase.", "Welcome."),
            ("You", "すみません、これをお願いします。", "Sumimasen, kore o onegai shimasu.", "Excuse me, I'll take this."),
            ("Clerk", "お弁当は温めますか。", "Obentou wa atatamemasu ka.", "Shall I heat up the bento?"),
            ("You", "はい、お願いします。", "Hai, onegai shimasu.", "Yes, please."),
            ("Clerk", "お箸はお付けしますか。", "Ohashi wa otsuke shimasu ka.", "Would you like chopsticks?"),
            ("You", "はい、一つお願いします。", "Hai, hitotsu onegai shimasu.", "Yes, one pair please."),
            ("Clerk", "袋はご利用ですか。三円かかります。", "Fukuro wa goriyou desu ka. San en kakarimasu.", "Do you need a bag? It's 3 yen."),
            ("You", "いいえ、大丈夫です。かばんに入れます。", "Iie, daijoubu desu. Kaban ni iremasu.", "No thanks. I'll put it in my bag."),
            ("Clerk", "ポイントカードはお持ちですか。", "Pointo kaado wa omochi desu ka.", "Do you have a point card?"),
            ("You", "いいえ、持っていません。", "Iie, motte imasen.", "No, I don't."),
            ("You", "あと、肉まんを一つください。", "Ato, nikuman o hitotsu kudasai.", "Also, one meat bun please."),
            ("Clerk", "肉まんですね。こちらの特製肉まんでよろしいですか。", "Nikuman desu ne. Kochira no tokusei nikuman de yoroshii desu ka.", "A meat bun. Is this premium one okay?"),
            ("You", "はい、それでいいです。", "Hai, sore de ii desu.", "Yes, that's fine."),
            ("Clerk", "お会計、九百八十円です。", "Okaikei, kyuuhyaku hachijuu en desu.", "Your total is 980 yen."),
            ("You", "千円でお願いします。", "Sen en de onegai shimasu.", "Here's 1,000 yen."),
            ("Clerk", "千円お預かりします。二十円のお返しです。", "Sen en oazukari shimasu. Nijuu en no okaeshi desu.", "Out of 1,000 yen. Here's 20 yen change."),
            ("You", "すみません、ATMはどこにありますか。", "Sumimasen, ee tii emu wa doko ni arimasu ka.", "Excuse me, where is the ATM?"),
            ("Clerk", "雑誌コーナーの横にございます。", "Zasshi koonaa no yoko ni gozaimasu.", "It's next to the magazine section."),
            ("You", "海外のカードも使えますか。", "Kaigai no kaado mo tsukaemasu ka.", "Can I use a foreign card?"),
            ("Clerk", "はい、ご利用いただけます。英語も選べますよ。", "Hai, goriyou itadakemasu. Eigo mo erabemasu yo.", "Yes, you can. You can choose English too."),
            ("You", "それから、切手も売っていますか。", "Sore kara, kitte mo utte imasu ka.", "Also, do you sell stamps?"),
            ("Clerk", "はい、何円の切手ですか。", "Hai, nan en no kitte desu ka.", "Yes, what value of stamp?"),
            ("You", "アメリカにはがきを送りたいんですが。", "Amerika ni hagaki o okuritain desu ga.", "I'd like to send a postcard to America."),
            ("Clerk", "海外へのはがきでしたら、百円の切手になります。", "Kaigai e no hagaki deshitara, hyaku en no kitte ni narimasu.", "For a postcard overseas, it's a 100-yen stamp."),
            ("You", "じゃあ、百円の切手を二枚ください。", "Jaa, hyaku en no kitte o nimai kudasai.", "Then two 100-yen stamps, please."),
            ("Clerk", "二百円です。お弁当、お待たせしました。熱いのでお気をつけください。", "Nihyaku en desu. Obentou, omatase shimashita. Atsui node oki o tsuke kudasai.", "That's 200 yen. Here's your bento. It's hot, so be careful."),
            ("You", "ありがとうございます。", "Arigatou gozaimasu.", "Thank you."),
            ("Clerk", "ありがとうございました。またお越しくださいませ。", "Arigatou gozaimashita. Mata okoshi kudasaimase.", "Thank you. Please come again."),
        ],
    ),
    scenario(
        "cafe-order",
        "Ordering at a café",
        "Choose size, hot or iced, and milk; add a snack; pay by tap; and ask about Wi-Fi and outlets.",
        setting="Coffee shop",
        category=CATEGORY,
        level="Beginner",
        lines=[
            ("Staff", "いらっしゃいませ。店内でお召し上がりですか。", "Irasshaimase. Tennai de omeshiagari desu ka.", "Welcome. Will you be having it here?"),
            ("You", "はい、ここで飲みます。", "Hai, koko de nomimasu.", "Yes, I'll drink it here."),
            ("Staff", "ご注文はお決まりですか。", "Gochuumon wa okimari desu ka.", "Have you decided on your order?"),
            ("You", "ええと、カフェラテをください。", "Eeto, kafe rate o kudasai.", "Um, a café latte, please."),
            ("Staff", "サイズはどうなさいますか。", "Saizu wa dou nasaimasu ka.", "What size would you like?"),
            ("You", "エムサイズでお願いします。", "Emu saizu de onegai shimasu.", "Medium, please."),
            ("Staff", "ホットとアイス、どちらになさいますか。", "Hotto to aisu, dochira ni nasaimasu ka.", "Hot or iced?"),
            ("You", "アイスでお願いします。", "Aisu de onegai shimasu.", "Iced, please."),
            ("Staff", "ミルクは、普通の牛乳と豆乳がございますが。", "Miruku wa, futsuu no gyuunyuu to tounyuu ga gozaimasu ga.", "For milk, we have regular milk and soy milk."),
            ("You", "豆乳にできますか。", "Tounyuu ni dekimasu ka.", "Can I have soy milk?"),
            ("Staff", "はい、プラス五十円になります。", "Hai, purasu gojuu en ni narimasu.", "Yes, that's 50 yen extra."),
            ("You", "大丈夫です。あと、このスコーンも一つください。", "Daijoubu desu. Ato, kono sukoon mo hitotsu kudasai.", "That's fine. And one of these scones, please."),
            ("Staff", "スコーンは温めますか。", "Sukoon wa atatamemasu ka.", "Shall I warm the scone?"),
            ("You", "はい、お願いします。", "Hai, onegai shimasu.", "Yes, please."),
            ("Staff", "以上でよろしいですか。", "Ijou de yoroshii desu ka.", "Will that be all?"),
            ("You", "はい、以上です。", "Hai, ijou desu.", "Yes, that's all."),
            ("Staff", "お会計、八百七十円です。", "Okaikei, happyaku nanajuu en desu.", "Your total is 870 yen."),
            ("You", "電子マネーで払えますか。", "Denshi manee de haraemasu ka.", "Can I pay with e-money?"),
            ("Staff", "はい、こちらにタッチしてください。", "Hai, kochira ni tacchi shite kudasai.", "Yes, please tap here."),
            ("Staff", "ありがとうございます。レシートはご利用ですか。", "Arigatou gozaimasu. Reshiito wa goriyou desu ka.", "Thank you. Would you like a receipt?"),
            ("You", "いいえ、大丈夫です。", "Iie, daijoubu desu.", "No, thank you."),
            ("Staff", "番号札をお持ちになって、お席でお待ちください。", "Bangoufuda o omochi ni natte, oseki de omachi kudasai.", "Please take this number tag and wait at your seat."),
            ("You", "すみません、ワイファイとコンセントはありますか。", "Sumimasen, waifai to konsento wa arimasu ka.", "Excuse me, is there Wi-Fi and a power outlet?"),
            ("Staff", "窓側のカウンター席に、コンセントがございます。", "Madogawa no kauntaa seki ni, konsento ga gozaimasu.", "There are outlets at the counter seats by the window."),
            ("Staff", "ワイファイのパスワードは、テーブルのカードに書いてあります。", "Waifai no pasuwaado wa, teeburu no kaado ni kaite arimasu.", "The Wi-Fi password is written on the card on the table."),
            ("You", "ありがとうございます。窓側に座ります。", "Arigatou gozaimasu. Madogawa ni suwarimasu.", "Thank you. I'll sit by the window."),
            ("Staff", "お待たせしました。アイスの豆乳ラテと、温めたスコーンです。", "Omatase shimashita. Aisu no tounyuu rate to, atatameta sukoon desu.", "Thank you for waiting. An iced soy latte and a warmed scone."),
            ("You", "ありがとうございます。いただきます。", "Arigatou gozaimasu. Itadakimasu.", "Thank you. Time to eat."),
        ],
    ),
    scenario(
        "ramen-shop",
        "Ramen with a ticket machine",
        "Use a meal-ticket machine, customize your noodles, and order a noodle refill.",
        setting="Ramen shop",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Staff", "いらっしゃいませ！先に食券をお買い求めください。", "Irasshaimase! Saki ni shokken o okaimotome kudasai.", "Welcome! Please buy a meal ticket first."),
            ("You", "食券ですか。すみません、使い方が分からないんですが。", "Shokken desu ka. Sumimasen, tsukaikata ga wakaranain desu ga.", "A meal ticket? Sorry, I don't know how to use the machine."),
            ("Staff", "大丈夫ですよ。まずお金を入れて、食べたいラーメンのボタンを押してください。", "Daijoubu desu yo. Mazu okane o irete, tabetai raamen no botan o oshite kudasai.", "No problem. First put in money, then press the button for the ramen you want."),
            ("You", "おすすめはどれですか。", "Osusume wa dore desu ka.", "Which one do you recommend?"),
            ("Staff", "一番人気は、この豚骨ラーメンです。", "Ichiban ninki wa, kono tonkotsu raamen desu.", "The most popular is this tonkotsu ramen."),
            ("You", "辛いですか。", "Karai desu ka.", "Is it spicy?"),
            ("Staff", "いいえ、辛くないです。辛いのがお好きなら、こちらの辛味噌ラーメンもありますよ。", "Iie, karakunai desu. Karai no ga osuki nara, kochira no karamiso raamen mo arimasu yo.", "No, it isn't. If you like spicy food, there's also this spicy miso ramen."),
            ("You", "じゃあ、豚骨ラーメンにします。味玉も追加できますか。", "Jaa, tonkotsu raamen ni shimasu. Ajitama mo tsuika dekimasu ka.", "Then I'll have the tonkotsu. Can I add a seasoned egg?"),
            ("Staff", "はい、下の段の「味玉」のボタンです。", "Hai, shita no dan no \"ajitama\" no botan desu.", "Yes, it's the \"ajitama\" button on the bottom row."),
            ("You", "買えました。どうぞ。", "Kaemashita. Douzo.", "Got them. Here you go."),
            ("Staff", "ありがとうございます。麺の硬さはどうしますか。", "Arigatou gozaimasu. Men no katasa wa dou shimasu ka.", "Thank you. How firm would you like the noodles?"),
            ("You", "硬さですか。普通でお願いします。", "Katasa desu ka. Futsuu de onegai shimasu.", "Firmness? Regular, please."),
            ("Staff", "味の濃さと油の量も、普通でよろしいですか。", "Aji no kosa to abura no ryou mo, futsuu de yoroshii desu ka.", "Regular flavor strength and oil too?"),
            ("You", "はい、全部普通でお願いします。", "Hai, zenbu futsuu de onegai shimasu.", "Yes, all regular, please."),
            ("Staff", "お好きな席にどうぞ。カウンターが空いています。", "Osuki na seki ni douzo. Kauntaa ga aite imasu.", "Sit anywhere you like. The counter is free."),
            ("You", "お水はどこですか。", "Omizu wa doko desu ka.", "Where is the water?"),
            ("Staff", "セルフサービスで、あちらにございます。", "Serufu saabisu de, achira ni gozaimasu.", "It's self-service, over there."),
            ("Staff", "お待たせしました。豚骨ラーメン、味玉付きです。", "Omatase shimashita. Tonkotsu raamen, ajitama tsuki desu.", "Thanks for waiting. Tonkotsu ramen with a seasoned egg."),
            ("You", "わあ、いいにおい。いただきます。", "Waa, ii nioi. Itadakimasu.", "Wow, it smells great. Let's eat."),
            ("Staff", "替え玉もできますので、言ってくださいね。", "Kaedama mo dekimasu node, itte kudasai ne.", "You can get a kaedama too, so just let us know."),
            ("You", "替え玉って何ですか。", "Kaedama tte nan desu ka.", "What's a kaedama?"),
            ("Staff", "麺のおかわりです。スープを残しておいてくださいね。", "Men no okawari desu. Suupu o nokoshite oite kudasai ne.", "It's a refill of noodles. Keep some soup left."),
            ("You", "すみません、替え玉をお願いします。", "Sumimasen, kaedama o onegai shimasu.", "Excuse me, a noodle refill, please."),
            ("Staff", "はい、替え玉一つ！百五十円です。", "Hai, kaedama hitotsu! Hyaku gojuu en desu.", "One refill! That's 150 yen."),
            ("You", "ごちそうさまでした。とてもおいしかったです。", "Gochisousama deshita. Totemo oishikatta desu.", "Thank you for the meal. It was delicious."),
            ("Staff", "ありがとうございました！またどうぞ！", "Arigatou gozaimashita! Mata douzo!", "Thank you! Come again!"),
        ],
    ),
    scenario(
        "sushi-counter",
        "At the sushi counter",
        "Sit at the counter, learn some sushi-shop words, and order piece by piece from the chef.",
        setting="Sushi restaurant",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Chef", "へい、らっしゃい！", "Hei, rasshai!", "Welcome!"),
            ("You", "こんばんは。一人ですが、カウンターに座ってもいいですか。", "Konbanwa. Hitori desu ga, kauntaa ni suwatte mo ii desu ka.", "Good evening. It's just me. May I sit at the counter?"),
            ("Chef", "どうぞどうぞ。お飲み物は？", "Douzo douzo. Onomimono wa?", "Please, go ahead. Something to drink?"),
            ("You", "温かいお茶をお願いします。", "Atatakai ocha o onegai shimasu.", "Hot tea, please."),
            ("Chef", "はい、あがり一つ！", "Hai, agari hitotsu!", "One agari!"),
            ("You", "「あがり」って何ですか。", "\"Agari\" tte nan desu ka.", "What's \"agari\"?"),
            ("Chef", "お寿司屋さんの言葉で、お茶のことですよ。", "Osushiyasan no kotoba de, ocha no koto desu yo.", "It's sushi-shop slang for tea."),
            ("You", "へえ、面白いですね。今日のおすすめは何ですか。", "Hee, omoshiroi desu ne. Kyou no osusume wa nan desu ka.", "Huh, interesting. What do you recommend today?"),
            ("Chef", "今日はいいマグロが入ってますよ。中トロがおすすめです。", "Kyou wa ii maguro ga haittemasu yo. Chuutoro ga osusume desu.", "We got good tuna in today. I recommend the medium-fatty tuna."),
            ("You", "じゃあ、中トロを二貫お願いします。", "Jaa, chuutoro o nikan onegai shimasu.", "Then two pieces of chutoro, please."),
            ("Chef", "わさびは大丈夫ですか。", "Wasabi wa daijoubu desu ka.", "Is wasabi okay?"),
            ("You", "はい、少しなら大丈夫です。", "Hai, sukoshi nara daijoubu desu.", "Yes, a little is fine."),
            ("Chef", "はい、中トロです。醤油はもう塗ってあるので、そのままどうぞ。", "Hai, chuutoro desu. Shouyu wa mou nutte aru node, sono mama douzo.", "Here's your chutoro. It already has soy sauce on it, so eat it as is."),
            ("You", "手で食べてもいいですか。", "Te de tabete mo ii desu ka.", "Can I eat it with my hands?"),
            ("Chef", "もちろん。お寿司は手で食べても大丈夫ですよ。", "Mochiron. Osushi wa te de tabete mo daijoubu desu yo.", "Of course. It's fine to eat sushi with your hands."),
            ("You", "とろけます！すごくおいしいです。", "Torokemasu! Sugoku oishii desu.", "It melts in my mouth! It's really delicious."),
            ("Chef", "ありがとうございます。次は何にしましょう。", "Arigatou gozaimasu. Tsugi wa nani ni shimashou.", "Thank you. What would you like next?"),
            ("You", "白身の魚は何がありますか。", "Shiromi no sakana wa nani ga arimasu ka.", "What white fish do you have?"),
            ("Chef", "タイとヒラメがあります。ヒラメは昆布締めにしてますよ。", "Tai to hirame ga arimasu. Hirame wa kobujime ni shitemasu yo.", "Sea bream and flounder. The flounder is cured in kelp."),
            ("You", "ヒラメをお願いします。それと、サーモンもください。", "Hirame o onegai shimasu. Sore to, saamon mo kudasai.", "Flounder, please. And some salmon too."),
            ("Chef", "はいよ。サーモンは炙りもできますけど、どうします？", "Hai yo. Saamon wa aburi mo dekimasu kedo, dou shimasu?", "Coming up. I can also sear the salmon. How would you like it?"),
            ("You", "炙りでお願いします。", "Aburi de onegai shimasu.", "Seared, please."),
            ("Chef", "お客さん、日本は長いんですか。", "Okyakusan, Nihon wa nagain desu ka.", "Have you been in Japan long?"),
            ("You", "いいえ、まだ一週間です。でも、毎日お寿司を食べています。", "Iie, mada isshuukan desu. Demo, mainichi osushi o tabete imasu.", "No, just a week. But I've had sushi every day."),
            ("Chef", "ははは、それはうれしいですね。", "Hahaha, sore wa ureshii desu ne.", "Ha ha, that makes me happy."),
            ("You", "最後に、玉子をお願いします。", "Saigo ni, tamago o onegai shimasu.", "Lastly, the egg, please."),
            ("Chef", "玉子は、店の味が一番分かるネタですよ。どうぞ。", "Tamago wa, mise no aji ga ichiban wakaru neta desu yo. Douzo.", "The egg is the piece that shows a shop's style best. Here you go."),
            ("You", "甘くておいしいです。お会計をお願いします。", "Amakute oishii desu. Okaikei o onegai shimasu.", "Sweet and delicious. The check, please."),
            ("Chef", "ありがとうございます。四千二百円です。", "Arigatou gozaimasu. Yonsen nihyaku en desu.", "Thank you. That's 4,200 yen."),
            ("You", "ごちそうさまでした。また来ます。", "Gochisousama deshita. Mata kimasu.", "Thank you for the meal. I'll come again."),
            ("Chef", "お待ちしてます！", "Omachi shitemasu!", "We'll be waiting!"),
        ],
    ),
    scenario(
        "cooking-curry",
        "Cooking curry with a friend",
        "Make Japanese curry rice at home: ingredients, cutting, simmering, and washing rice. Casual speech.",
        setting="Yuki's kitchen",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Yuki", "今日は一緒にカレーを作ろう！", "Kyou wa issho ni karee o tsukurou!", "Let's make curry together today!"),
            ("You", "いいね！日本のカレーを作るのは初めて。", "Ii ne! Nihon no karee o tsukuru no wa hajimete.", "Great! It's my first time making Japanese curry."),
            ("Yuki", "簡単だよ。まず、材料を準備しよう。", "Kantan da yo. Mazu, zairyou o junbi shiyou.", "It's easy. First, let's get the ingredients ready."),
            ("You", "何が必要？", "Nani ga hitsuyou?", "What do we need?"),
            ("Yuki", "玉ねぎ、にんじん、じゃがいも、それとお肉。今日は豚肉にしたよ。", "Tamanegi, ninjin, jagaimo, sore to oniku. Kyou wa butaniku ni shita yo.", "Onions, carrots, potatoes, and meat. I went with pork today."),
            ("You", "カレーのルーもあるね。", "Karee no ruu mo aru ne.", "There's curry roux too."),
            ("Yuki", "うん、中辛にしたけど、大丈夫？", "Un, chuukara ni shita kedo, daijoubu?", "Yeah, I got medium hot. Is that okay?"),
            ("You", "大丈夫。辛いの好きだよ。", "Daijoubu. Karai no suki da yo.", "That's fine. I like spicy food."),
            ("Yuki", "じゃあ、にんじんとじゃがいもの皮をむいてくれる？", "Jaa, ninjin to jagaimo no kawa o muite kureru?", "Then could you peel the carrots and potatoes?"),
            ("You", "オッケー。どのくらいの大きさに切ればいい？", "Okkee. Dono kurai no ookisa ni kireba ii?", "Okay. How big should I cut them?"),
            ("Yuki", "一口サイズでいいよ。私は玉ねぎを切るね。", "Hitokuchi saizu de ii yo. Watashi wa tamanegi o kiru ne.", "Bite-size is fine. I'll cut the onions."),
            ("You", "玉ねぎって、目が痛くならない？", "Tamanegi tte, me ga itaku naranai?", "Don't onions make your eyes sting?"),
            ("Yuki", "なるよ。もう涙が出てきた。", "Naru yo. Mou namida ga dete kita.", "They do. I'm already tearing up."),
            ("You", "切り終わったよ。次は？", "Kiriowatta yo. Tsugi wa?", "I'm done cutting. What's next?"),
            ("Yuki", "鍋に油を入れて、まずお肉を炒めよう。", "Nabe ni abura o irete, mazu oniku o itameyou.", "Put oil in the pot and let's fry the meat first."),
            ("You", "肉の色が変わったら、野菜を入れる？", "Niku no iro ga kawattara, yasai o ireru?", "Once the meat changes color, do we add the vegetables?"),
            ("Yuki", "そうそう。玉ねぎがしんなりするまで炒めてね。", "Sou sou. Tamanegi ga shinnari suru made itamete ne.", "Exactly. Fry until the onions go soft."),
            ("You", "いいにおいがしてきた。", "Ii nioi ga shite kita.", "It's starting to smell good."),
            ("Yuki", "次に水を入れて、二十分ぐらい煮込むよ。", "Tsugi ni mizu o irete, nijuppun gurai nikomu yo.", "Next we add water and simmer for about twenty minutes."),
            ("You", "その間に何をする？", "Sono aida ni nani o suru?", "What do we do in the meantime?"),
            ("Yuki", "ご飯を炊こう。お米を洗ってくれる？", "Gohan o takou. Okome o aratte kureru?", "Let's cook the rice. Can you wash the rice?"),
            ("You", "お米は何回洗うの？", "Okome wa nankai arau no?", "How many times do you wash rice?"),
            ("Yuki", "水が透明に近くなるまで、三回ぐらいかな。", "Mizu ga toumei ni chikaku naru made, sankai gurai ka na.", "About three times, until the water is nearly clear."),
            ("You", "野菜が柔らかくなったよ。", "Yasai ga yawarakaku natta yo.", "The vegetables are soft now."),
            ("Yuki", "じゃあ、火を止めて、ルーを入れて溶かそう。", "Jaa, hi o tomete, ruu o irete tokasou.", "Then turn off the heat, add the roux, and let it melt."),
            ("You", "火を止めるの？", "Hi o tomeru no?", "We turn the heat off?"),
            ("Yuki", "うん、そのほうがダマにならないんだ。溶けたら、また弱火で十分ぐらい煮るよ。", "Un, sono hou ga dama ni naranain da. Toketara, mata yowabi de juppun gurai niru yo.", "Yeah, that way it doesn't get lumpy. Once it melts, we simmer on low for about ten minutes."),
            ("You", "とろとろになってきた！", "Torotoro ni natte kita!", "It's getting nice and thick!"),
            ("Yuki", "完成！ご飯をよそって、カレーをかけよう。", "Kansei! Gohan o yosotte, karee o kakeyou.", "Done! Let's serve the rice and pour the curry over it."),
            ("You", "いただきます！すごくおいしい！", "Itadakimasu! Sugoku oishii!", "Let's eat! This is so good!"),
            ("Yuki", "よかった。カレーは次の日のほうが、もっとおいしいんだよ。", "Yokatta. Karee wa tsugi no hi no hou ga, motto oishiin da yo.", "I'm glad. Curry tastes even better the next day."),
            ("You", "じゃあ、明日も食べに来ていい？", "Jaa, ashita mo tabe ni kite ii?", "Then can I come eat it tomorrow too?"),
            ("Yuki", "もちろん！", "Mochiron!", "Of course!"),
        ],
    ),
    scenario(
        "izakaya-night",
        "A night at the izakaya",
        "Go drinking with a coworker: seating, the mystery appetizer, ordering yakitori, and splitting the bill. Casual speech.",
        setting="Izakaya",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("Kenta", "ここだよ。いつも来る居酒屋。", "Koko da yo. Itsumo kuru izakaya.", "This is it. The izakaya I always come to."),
            ("You", "いい雰囲気だね。", "Ii fun'iki da ne.", "Nice atmosphere."),
            ("Staff", "いらっしゃいませ！何名様ですか。", "Irasshaimase! Nanmei-sama desu ka.", "Welcome! How many people?"),
            ("Kenta", "二人です。", "Futari desu.", "Two."),
            ("Staff", "お座敷とテーブル、どちらがよろしいですか。", "Ozashiki to teeburu, dochira ga yoroshii desu ka.", "Tatami seating or a table?"),
            ("Kenta", "せっかくだから、座敷にしようか。", "Sekkaku dakara, zashiki ni shiyou ka.", "Since we're here, shall we do tatami?"),
            ("You", "うん、いいね。", "Un, ii ne.", "Yeah, sounds good."),
            ("Staff", "こちらへどうぞ。お飲み物はお決まりですか。", "Kochira e douzo. Onomimono wa okimari desu ka.", "This way, please. Have you decided on drinks?"),
            ("Kenta", "とりあえず生ビール。コナーは？", "Toriaezu nama biiru. Konaa wa?", "A draft beer to start. What about you, Connor?"),
            ("You", "僕はウーロン茶で。お酒はあまり強くないんだ。", "Boku wa uuroncha de. Osake wa amari tsuyokunain da.", "Oolong tea for me. I can't hold my drink very well."),
            ("Staff", "生一つ、ウーロン茶一つですね。こちら、お通しです。", "Nama hitotsu, uuroncha hitotsu desu ne. Kochira, otooshi desu.", "One draft, one oolong tea. And here's your otoshi."),
            ("You", "お通しって、注文してないけど。", "Otooshi tte, chuumon shitenai kedo.", "Otoshi? We didn't order this."),
            ("Kenta", "居酒屋で最初に出てくる小皿料理なんだ。席料みたいなものだよ。", "Izakaya de saisho ni dete kuru kozara ryouri nan da. Sekiryou mitai na mono da yo.", "It's the small dish they bring first at izakayas. It's kind of like a cover charge."),
            ("You", "へえ、そうなんだ。", "Hee, sou nan da.", "Huh, I didn't know that."),
            ("Kenta", "何食べたい？ここは焼き鳥がおいしいよ。", "Nani tabetai? Koko wa yakitori ga oishii yo.", "What do you want to eat? The yakitori here is great."),
            ("You", "焼き鳥、食べたい！あと、枝豆と唐揚げも。", "Yakitori, tabetai! Ato, edamame to karaage mo.", "I want yakitori! And edamame and fried chicken too."),
            ("Kenta", "すみません、注文お願いします。", "Sumimasen, chuumon onegai shimasu.", "Excuse me, we'd like to order."),
            ("Staff", "はい、どうぞ。", "Hai, douzo.", "Yes, go ahead."),
            ("Kenta", "焼き鳥の盛り合わせを塩で。それと、枝豆と唐揚げをお願いします。", "Yakitori no moriawase o shio de. Sore to, edamame to karaage o onegai shimasu.", "An assorted yakitori plate with salt. And edamame and fried chicken, please."),
            ("Staff", "盛り合わせを塩で、枝豆、唐揚げですね。少々お待ちください。", "Moriawase o shio de, edamame, karaage desu ne. Shoushou omachi kudasai.", "Assorted with salt, edamame, and fried chicken. One moment please."),
            ("Kenta", "じゃあ、乾杯！", "Jaa, kanpai!", "Well then, cheers!"),
            ("You", "乾杯！今日は誘ってくれてありがとう。", "Kanpai! Kyou wa sasotte kurete arigatou.", "Cheers! Thanks for inviting me today."),
            ("Kenta", "こちらこそ。日本の生活には慣れた？", "Kochira koso. Nihon no seikatsu ni wa nareta?", "Thanks for coming. Have you gotten used to life in Japan?"),
            ("You", "だいぶ慣れたよ。でも、まだ敬語が難しい。", "Daibu nareta yo. Demo, mada keigo ga muzukashii.", "Mostly. But keigo is still hard."),
            ("Kenta", "日本人でも難しいから、大丈夫だよ。", "Nihonjin demo muzukashii kara, daijoubu da yo.", "It's hard even for Japanese people, so don't worry."),
            ("Staff", "お待たせしました。焼き鳥の盛り合わせです。", "Omatase shimashita. Yakitori no moriawase desu.", "Thanks for waiting. Your assorted yakitori."),
            ("You", "おいしそう！これは何？", "Oishisou! Kore wa nani?", "Looks delicious! What's this one?"),
            ("Kenta", "それはつくね。鶏肉の団子だよ。こっちはねぎま。", "Sore wa tsukune. Toriniku no dango da yo. Kocchi wa negima.", "That's tsukune, chicken meatballs. This one is negima, chicken and green onion."),
            ("You", "うん、おいしい！もう一本食べたいな。", "Un, oishii! Mou ippon tabetai na.", "Mm, delicious! I want another skewer."),
            ("Kenta", "追加しよう。すみません、つくねを二本追加で。", "Tsuika shiyou. Sumimasen, tsukune o nihon tsuika de.", "Let's order more. Excuse me, two more tsukune please."),
            ("Staff", "かしこまりました！", "Kashikomarimashita!", "Right away!"),
            ("Kenta", "そろそろ帰ろうか。明日も仕事だし。", "Sorosoro kaerou ka. Ashita mo shigoto da shi.", "Shall we head home soon? We've got work tomorrow."),
            ("You", "そうだね。お会計しよう。", "Sou da ne. Okaikei shiyou.", "Yeah. Let's get the bill."),
            ("Kenta", "すみません、お会計お願いします。", "Sumimasen, okaikei onegai shimasu.", "Excuse me, the check please."),
            ("Staff", "ありがとうございます。全部で五千四百円になります。", "Arigatou gozaimasu. Zenbu de gosen yonhyaku en ni narimasu.", "Thank you. That comes to 5,400 yen."),
            ("You", "割り勘にしよう。一人二千七百円だね。", "Warikan ni shiyou. Hitori nisen nanahyaku en da ne.", "Let's split it. That's 2,700 yen each."),
            ("Kenta", "オッケー。また来ようね。", "Okkee. Mata koyou ne.", "Okay. Let's come back again."),
        ],
    ),
]
