from app.services.listening_content.base import scenario

CATEGORY = "Shopping & services"

SHOPPING_SCENARIOS = [
    scenario(
        "clothes-shopping",
        "Buying a winter coat",
        "Ask about colors and materials, try it on, deal with Japanese sizes, and shop tax-free.",
        setting="Clothing store",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Staff", "いらっしゃいませ。何かお探しですか。", "Irasshaimase. Nanika osagashi desu ka.", "Welcome. Are you looking for something?"),
            ("You", "はい、冬のコートを探しています。", "Hai, fuyu no kooto o sagashite imasu.", "Yes, I'm looking for a winter coat."),
            ("Staff", "コートでしたら、こちらにございます。どんな色がお好きですか。", "Kooto deshitara, kochira ni gozaimasu. Donna iro ga osuki desu ka.", "Coats are over here. What colors do you like?"),
            ("You", "黒か紺がいいです。", "Kuro ka kon ga ii desu.", "Black or navy."),
            ("Staff", "こちらの紺のコートは今年の新作で、とても暖かいですよ。", "Kochira no kon no kooto wa kotoshi no shinsaku de, totemo atatakai desu yo.", "This navy coat is new this year and very warm."),
            ("You", "軽いですね。素材は何ですか。", "Karui desu ne. Sozai wa nan desu ka.", "It's light. What's it made of?"),
            ("Staff", "ウールとダウンです。家で洗濯もできます。", "Uuru to daun desu. Ie de sentaku mo dekimasu.", "Wool and down. You can wash it at home too."),
            ("You", "試着してもいいですか。", "Shichaku shite mo ii desu ka.", "May I try it on?"),
            ("Staff", "もちろんです。サイズはおいくつですか。", "Mochiron desu. Saizu wa oikutsu desu ka.", "Of course. What size are you?"),
            ("You", "アメリカのサイズだとエムなんですが、日本のサイズはよく分かりません。", "Amerika no saizu da to emu nan desu ga, Nihon no saizu wa yoku wakarimasen.", "In American sizes I'm a medium, but I don't really know Japanese sizes."),
            ("Staff", "日本のサイズは少し小さめなので、エルをお試しください。", "Nihon no saizu wa sukoshi chiisame na node, eru o otameshi kudasai.", "Japanese sizes run a little small, so please try the large."),
            ("Staff", "試着室はこちらです。どうぞ。", "Shichakushitsu wa kochira desu. Douzo.", "The fitting room is over here. Go ahead."),
            ("Staff", "いかがですか。", "Ikaga desu ka.", "How is it?"),
            ("You", "サイズはちょうどいいですけど、袖が少し長いです。", "Saizu wa choudo ii desu kedo, sode ga sukoshi nagai desu.", "The size is just right, but the sleeves are a bit long."),
            ("Staff", "袖のお直しもできますよ。三日ほどかかりますが。", "Sode no onaoshi mo dekimasu yo. Mikka hodo kakarimasu ga.", "We can alter the sleeves. It takes about three days, though."),
            ("You", "三日ですか。あさってには日本を出るので、ちょっと難しいです。", "Mikka desu ka. Asatte ni wa Nihon o deru node, chotto muzukashii desu.", "Three days? I leave Japan the day after tomorrow, so that's tricky."),
            ("Staff", "それでしたら、こちらの少し短めのデザインはいかがでしょうか。", "Sore deshitara, kochira no sukoshi mijikame no dezain wa ikaga deshou ka.", "In that case, how about this slightly shorter design?"),
            ("You", "あ、これはいいですね。袖もちょうどいいです。", "A, kore wa ii desu ne. Sode mo choudo ii desu.", "Oh, this is nice. The sleeves are just right too."),
            ("You", "いくらですか。", "Ikura desu ka.", "How much is it?"),
            ("Staff", "一万九千八百円です。今週はセールで、二割引きになります。", "Ichiman kyuusen happyaku en desu. Konshuu wa seeru de, niwaribiki ni narimasu.", "It's 19,800 yen. There's a sale this week, so it's 20% off."),
            ("You", "免税はできますか。", "Menzei wa dekimasu ka.", "Can I buy it tax-free?"),
            ("Staff", "はい、五千円以上で、パスポートがあれば免税になります。", "Hai, gosen en ijou de, pasupooto ga areba menzei ni narimasu.", "Yes, over 5,000 yen with your passport, it's tax-free."),
            ("You", "じゃあ、これにします。", "Jaa, kore ni shimasu.", "Then I'll take this one."),
            ("Staff", "ありがとうございます。タグはお切りしますか。", "Arigatou gozaimasu. Tagu wa okiri shimasu ka.", "Thank you. Shall I cut off the tags?"),
            ("You", "はい、すぐ着たいので、切ってください。", "Hai, sugu kitai node, kitte kudasai.", "Yes, I want to wear it right away, so please cut them."),
            ("Staff", "かしこまりました。外は寒いので、ちょうどよかったですね。", "Kashikomarimashita. Soto wa samui node, choudo yokatta desu ne.", "Certainly. It's cold outside, so perfect timing."),
        ],
    ),
    scenario(
        "phone-sim",
        "SIM card and charger",
        "Get a travel SIM set up, buy a charger, and find out what you can take on a plane.",
        setting="Electronics store",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("You", "すみません、旅行者用のシムカードはありますか。", "Sumimasen, ryokousha you no shimu kaado wa arimasu ka.", "Excuse me, do you have SIM cards for travelers?"),
            ("Staff", "はい、ございます。データだけのタイプと、電話もできるタイプがあります。", "Hai, gozaimasu. Deeta dake no taipu to, denwa mo dekiru taipu ga arimasu.", "Yes. There's a data-only type and one you can also call with."),
            ("You", "データだけで大丈夫です。どのくらいの量がありますか。", "Deeta dake de daijoubu desu. Dono kurai no ryou ga arimasu ka.", "Data only is fine. How much data do they have?"),
            ("Staff", "十日間で十ギガのものと、三十日間で二十ギガのものがあります。", "Tooka kan de juu giga no mono to, sanjuunichi kan de nijuu giga no mono ga arimasu.", "There's 10 GB for ten days and 20 GB for thirty days."),
            ("You", "二週間いるので、三十日間のほうがいいですね。", "Nishuukan iru node, sanjuunichi kan no hou ga ii desu ne.", "I'm here for two weeks, so the thirty-day one is better."),
            ("Staff", "こちらは四千五百円です。お客様のスマホは、シムフリーですか。", "Kochira wa yonsen gohyaku en desu. Okyakusama no sumaho wa, shimu furii desu ka.", "That's 4,500 yen. Is your phone unlocked?"),
            ("You", "たぶん大丈夫だと思いますが、確認してもらえますか。", "Tabun daijoubu da to omoimasu ga, kakunin shite moraemasu ka.", "I think so, but could you check for me?"),
            ("Staff", "かしこまりました。少しお借りしますね。", "Kashikomarimashita. Sukoshi okari shimasu ne.", "Certainly. Let me borrow it for a moment."),
            ("Staff", "はい、使えます。設定もこちらでいたしましょうか。", "Hai, tsukaemasu. Settei mo kochira de itashimashou ka.", "Yes, it works. Shall I set it up for you too?"),
            ("You", "お願いします。助かります。", "Onegai shimasu. Tasukarimasu.", "Yes please. That's a big help."),
            ("Staff", "設定が終わりました。インターネットにつながるか、確認してください。", "Settei ga owarimashita. Intaanetto ni tsunagaru ka, kakunin shite kudasai.", "The setup is done. Please check that it connects to the internet."),
            ("You", "つながりました！ありがとうございます。", "Tsunagarimashita! Arigatou gozaimasu.", "It's connected! Thank you."),
            ("You", "あと、充電器も探しているんですが。", "Ato, juudenki mo sagashite irun desu ga.", "Also, I'm looking for a charger."),
            ("Staff", "どのタイプのケーブルですか。", "Dono taipu no keeburu desu ka.", "What type of cable?"),
            ("You", "ユーエスビーのシーです。", "Yuu esu bii no shii desu.", "USB-C."),
            ("Staff", "こちらの急速充電器はいかがですか。差し込み口が二つあります。", "Kochira no kyuusoku juudenki wa ikaga desu ka. Sashikomiguchi ga futatsu arimasu.", "How about this fast charger? It has two ports."),
            ("You", "アメリカでも使えますか。", "Amerika demo tsukaemasu ka.", "Can I use it in America too?"),
            ("Staff", "はい、日本とアメリカはコンセントの形が同じなので、そのまま使えますよ。", "Hai, Nihon to Amerika wa konsento no katachi ga onaji na node, sono mama tsukaemasu yo.", "Yes, Japan and America use the same plug shape, so it works as is."),
            ("You", "それはいいですね。モバイルバッテリーもありますか。", "Sore wa ii desu ne. Mobairu batterii mo arimasu ka.", "Great. Do you have portable batteries too?"),
            ("Staff", "はい、こちらの一万ミリアンペアのものが人気です。飛行機にも持ち込めます。", "Hai, kochira no ichiman miri anpea no mono ga ninki desu. Hikouki ni mo mochikomemasu.", "Yes, this 10,000 mAh one is popular. You can bring it on planes too."),
            ("You", "スーツケースに入れても大丈夫ですか。", "Suutsukeesu ni irete mo daijoubu desu ka.", "Is it okay to pack it in my suitcase?"),
            ("Staff", "いいえ、モバイルバッテリーは預け荷物に入れられないので、手荷物で持って行ってください。", "Iie, mobairu batterii wa azuke nimotsu ni irerarenai node, tenimotsu de motte itte kudasai.", "No, portable batteries can't go in checked luggage, so carry it in your hand luggage."),
            ("You", "分かりました。じゃあ、全部お願いします。", "Wakarimashita. Jaa, zenbu onegai shimasu.", "Got it. Then I'll take all of these."),
            ("Staff", "ありがとうございます。全部で九千八百円になります。", "Arigatou gozaimasu. Zenbu de kyuusen happyaku en ni narimasu.", "Thank you. That comes to 9,800 yen."),
        ],
    ),
    scenario(
        "pharmacy",
        "At the pharmacy",
        "Describe cold symptoms, answer the pharmacist's questions, and learn how to take the medicine.",
        setting="Drugstore",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("You", "すみません、風邪薬はありますか。", "Sumimasen, kazegusuri wa arimasu ka.", "Excuse me, do you have cold medicine?"),
            ("Pharmacist", "はい、ございます。どんな症状ですか。", "Hai, gozaimasu. Donna shoujou desu ka.", "Yes, we do. What are your symptoms?"),
            ("You", "昨日の夜から、のどが痛くて、鼻水も出ます。", "Kinou no yoru kara, nodo ga itakute, hanamizu mo demasu.", "Since last night my throat has been sore and my nose is running."),
            ("Pharmacist", "熱はありますか。", "Netsu wa arimasu ka.", "Do you have a fever?"),
            ("You", "少しあると思います。体がだるいです。", "Sukoshi aru to omoimasu. Karada ga darui desu.", "I think I have a slight one. I feel sluggish."),
            ("Pharmacist", "咳は出ますか。", "Seki wa demasu ka.", "Are you coughing?"),
            ("You", "いいえ、咳はあまり出ません。", "Iie, seki wa amari demasen.", "No, not much."),
            ("Pharmacist", "何か薬のアレルギーはありますか。", "Nanika kusuri no arerugii wa arimasu ka.", "Are you allergic to any medicine?"),
            ("You", "いいえ、ありません。", "Iie, arimasen.", "No, I'm not."),
            ("Pharmacist", "今、ほかに飲んでいる薬はありますか。", "Ima, hoka ni nonde iru kusuri wa arimasu ka.", "Are you taking any other medicine right now?"),
            ("You", "いいえ、何も飲んでいません。", "Iie, nani mo nonde imasen.", "No, nothing."),
            ("Pharmacist", "それでしたら、こちらの総合風邪薬がいいと思います。", "Sore deshitara, kochira no sougou kazegusuri ga ii to omoimasu.", "In that case, I think this all-in-one cold medicine is good."),
            ("Pharmacist", "のどの痛みと鼻水、熱に効きます。", "Nodo no itami to hanamizu, netsu ni kikimasu.", "It works on sore throats, runny noses, and fevers."),
            ("You", "どうやって飲みますか。", "Dou yatte nomimasu ka.", "How do I take it?"),
            ("Pharmacist", "一日三回、食後に二錠ずつ飲んでください。", "Ichinichi sankai, shokugo ni nijou zutsu nonde kudasai.", "Take two tablets three times a day, after meals."),
            ("You", "食後ですね。眠くなりますか。", "Shokugo desu ne. Nemuku narimasu ka.", "After meals. Will it make me sleepy?"),
            ("Pharmacist", "はい、少し眠くなることがあるので、運転はしないでください。", "Hai, sukoshi nemuku naru koto ga aru node, unten wa shinaide kudasai.", "Yes, it can make you a little drowsy, so please don't drive."),
            ("You", "分かりました。のど飴もありますか。", "Wakarimashita. Nodoame mo arimasu ka.", "Understood. Do you have throat lozenges too?"),
            ("Pharmacist", "レジの横にございます。はちみつレモン味が人気ですよ。", "Reji no yoko ni gozaimasu. Hachimitsu remon aji ga ninki desu yo.", "They're next to the register. Honey lemon is popular."),
            ("You", "じゃあ、それも一つお願いします。", "Jaa, sore mo hitotsu onegai shimasu.", "Then I'll take one of those too."),
            ("Pharmacist", "三日飲んでもよくならなかったら、病院に行ってくださいね。", "Mikka nonde mo yoku naranakattara, byouin ni itte kudasai ne.", "If you're not better after three days, please see a doctor."),
            ("You", "近くに英語が話せる病院はありますか。", "Chikaku ni eigo ga hanaseru byouin wa arimasu ka.", "Is there a clinic nearby where they speak English?"),
            ("Pharmacist", "駅の反対側に、国際クリニックがあります。地図を書きましょうか。", "Eki no hantaigawa ni, kokusai kurinikku ga arimasu. Chizu o kakimashou ka.", "There's an international clinic on the other side of the station. Shall I draw you a map?"),
            ("You", "ありがとうございます。お願いします。", "Arigatou gozaimasu. Onegai shimasu.", "Thank you. Yes, please."),
            ("Pharmacist", "どうぞ。今日は温かくして、早く寝てくださいね。", "Douzo. Kyou wa atatakaku shite, hayaku nete kudasai ne.", "Here you are. Keep warm today and go to bed early."),
            ("You", "はい、そうします。ありがとうございました。", "Hai, sou shimasu. Arigatou gozaimashita.", "I will. Thank you very much."),
            ("Pharmacist", "お大事に。", "Odaiji ni.", "Take care of yourself."),
        ],
    ),
    scenario(
        "post-office",
        "Mailing a package home",
        "Send a box overseas: contents, airmail or sea mail, customs form, tracking, and insurance.",
        setting="Post office",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("You", "すみません、この荷物をアメリカに送りたいんですが。", "Sumimasen, kono nimotsu o Amerika ni okuritain desu ga.", "Excuse me, I'd like to send this package to America."),
            ("Clerk", "かしこまりました。中身は何ですか。", "Kashikomarimashita. Nakami wa nan desu ka.", "Certainly. What's inside?"),
            ("You", "服とお土産のお菓子と、本です。", "Fuku to omiyage no okashi to, hon desu.", "Clothes, snacks as souvenirs, and books."),
            ("Clerk", "電池や液体は入っていませんか。", "Denchi ya ekitai wa haitte imasen ka.", "No batteries or liquids inside?"),
            ("You", "いいえ、入っていません。", "Iie, haitte imasen.", "No, none."),
            ("Clerk", "では、送る方法を選んでください。航空便と船便があります。", "Dewa, okuru houhou o erande kudasai. Koukuubin to funabin ga arimasu.", "Then please choose a shipping method. There's airmail and sea mail."),
            ("You", "それぞれ、どのくらいかかりますか。", "Sorezore, dono kurai kakarimasu ka.", "How long does each take?"),
            ("Clerk", "航空便は一週間ぐらい、船便は二か月ぐらいかかります。", "Koukuubin wa isshuukan gurai, funabin wa nikagetsu gurai kakarimasu.", "Airmail takes about a week, and sea mail about two months."),
            ("You", "値段はどのくらい違いますか。", "Nedan wa dono kurai chigaimasu ka.", "How different are the prices?"),
            ("Clerk", "まず重さを量りますね。三キロですね。", "Mazu omosa o hakarimasu ne. Sankiro desu ne.", "Let me weigh it first. Three kilos."),
            ("Clerk", "航空便だと八千円ぐらい、船便だと四千円ぐらいです。", "Koukuubin da to hassen en gurai, funabin da to yonsen en gurai desu.", "About 8,000 yen by air, or about 4,000 yen by sea."),
            ("You", "急いでいないので、船便でお願いします。", "Isoide inai node, funabin de onegai shimasu.", "I'm not in a hurry, so sea mail please."),
            ("Clerk", "では、この伝票に記入してください。中身と値段も書いてくださいね。", "Dewa, kono denpyou ni kinyuu shite kudasai. Nakami to nedan mo kaite kudasai ne.", "Then please fill out this form. Write the contents and their value too."),
            ("You", "値段は大体でいいですか。", "Nedan wa daitai de ii desu ka.", "Is a rough value okay?"),
            ("Clerk", "はい、大体で大丈夫です。英語で書いてもいいですよ。", "Hai, daitai de daijoubu desu. Eigo de kaite mo ii desu yo.", "Yes, roughly is fine. You can write it in English."),
            ("You", "箱が少し弱いんですが、大丈夫でしょうか。", "Hako ga sukoshi yowain desu ga, daijoubu deshou ka.", "The box is a bit flimsy. Will it be okay?"),
            ("Clerk", "船便は時間がかかるので、テープでしっかり補強しましょう。", "Funabin wa jikan ga kakaru node, teepu de shikkari hokyou shimashou.", "Sea mail takes a while, so let's reinforce it well with tape."),
            ("You", "ありがとうございます。書き終わりました。", "Arigatou gozaimasu. Kakiowarimashita.", "Thank you. I've finished filling it out."),
            ("Clerk", "追跡番号はこちらです。インターネットで確認できます。", "Tsuiseki bangou wa kochira desu. Intaanetto de kakunin dekimasu.", "Here's your tracking number. You can check it online."),
            ("You", "保険は付いていますか。", "Hoken wa tsuite imasu ka.", "Is it insured?"),
            ("Clerk", "二万円までの補償が付いています。", "Niman en made no hoshou ga tsuite imasu.", "It's covered up to 20,000 yen."),
            ("You", "分かりました。それでお願いします。", "Wakarimashita. Sore de onegai shimasu.", "Okay. That works."),
            ("Clerk", "全部で四千二百円です。", "Zenbu de yonsen nihyaku en desu.", "That's 4,200 yen in total."),
            ("You", "カードは使えますか。", "Kaado wa tsukaemasu ka.", "Can I use a card?"),
            ("Clerk", "はい、使えます。ありがとうございました。", "Hai, tsukaemasu. Arigatou gozaimashita.", "Yes, you can. Thank you very much."),
        ],
    ),
    scenario(
        "hair-salon",
        "Getting a haircut",
        "Explain the cut you want, handle the shampoo small talk, and ask for small adjustments.",
        setting="Hair salon",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Stylist", "いらっしゃいませ。ご予約のお客様ですか。", "Irasshaimase. Goyoyaku no okyakusama desu ka.", "Welcome. Do you have an appointment?"),
            ("You", "はい、三時に予約したコナーです。", "Hai, sanji ni yoyaku shita Konaa desu.", "Yes, I'm Connor. I booked for three o'clock."),
            ("Stylist", "お待ちしておりました。こちらへどうぞ。上着をお預かりしますね。", "Omachi shite orimashita. Kochira e douzo. Uwagi o oazukari shimasu ne.", "We've been expecting you. This way, please. I'll take your jacket."),
            ("Stylist", "今日はどうなさいますか。", "Kyou wa dou nasaimasu ka.", "What would you like today?"),
            ("You", "カットをお願いします。全体的に短くしたいです。", "Katto o onegai shimasu. Zentaiteki ni mijikaku shitai desu.", "A cut, please. I'd like it shorter all over."),
            ("Stylist", "どのくらい切りますか。", "Dono kurai kirimasu ka.", "How much should I take off?"),
            ("You", "横と後ろは三センチぐらい、上は少しだけ切ってください。", "Yoko to ushiro wa sansenchi gurai, ue wa sukoshi dake kitte kudasai.", "About three centimeters on the sides and back, and just a little on top."),
            ("Stylist", "前髪はどうしますか。", "Maegami wa dou shimasu ka.", "What about your bangs?"),
            ("You", "眉毛にかからないぐらいでお願いします。", "Mayuge ni kakaranai gurai de onegai shimasu.", "Short enough that they don't cover my eyebrows, please."),
            ("Stylist", "写真などはありますか。", "Shashin nado wa arimasu ka.", "Do you have a photo or anything?"),
            ("You", "はい、こんな感じにしたいです。", "Hai, konna kanji ni shitai desu.", "Yes, I'd like it like this."),
            ("Stylist", "いいですね。かしこまりました。先にシャンプーをしますね。", "Ii desu ne. Kashikomarimashita. Saki ni shanpuu o shimasu ne.", "Nice. Got it. I'll shampoo first."),
            ("Stylist", "お湯の温度は大丈夫ですか。", "Oyu no ondo wa daijoubu desu ka.", "Is the water temperature okay?"),
            ("You", "ちょうどいいです。", "Choudo ii desu.", "It's just right."),
            ("Stylist", "かゆいところはございませんか。", "Kayui tokoro wa gozaimasen ka.", "Is there anywhere that's itchy?"),
            ("You", "大丈夫です。気持ちいいです。", "Daijoubu desu. Kimochi ii desu.", "I'm fine. It feels nice."),
            ("Stylist", "では、切っていきますね。お仕事は何をされているんですか。", "Dewa, kitte ikimasu ne. Oshigoto wa nani o sarete irun desu ka.", "I'll start cutting now. What do you do for work?"),
            ("You", "ソフトウェアのエンジニアです。今は東京で働いています。", "Sofutowea no enjinia desu. Ima wa Toukyou de hataraite imasu.", "I'm a software engineer. I work in Tokyo now."),
            ("Stylist", "すごいですね。日本に来て、どのくらいですか。", "Sugoi desu ne. Nihon ni kite, dono kurai desu ka.", "Impressive. How long have you been in Japan?"),
            ("You", "半年ぐらいです。", "Hantoshi gurai desu.", "About six months."),
            ("Stylist", "長さはこのくらいで、いかがですか。", "Nagasa wa kono kurai de, ikaga desu ka.", "How's this length?"),
            ("You", "もう少しだけ、横を短くしてください。", "Mou sukoshi dake, yoko o mijikaku shite kudasai.", "A little shorter on the sides, please."),
            ("Stylist", "はい。これでどうでしょう。", "Hai. Kore de dou deshou.", "Sure. How about this?"),
            ("You", "ばっちりです！", "Bacchiri desu!", "Perfect!"),
            ("Stylist", "ワックスを付けてもいいですか。", "Wakkusu o tsukete mo ii desu ka.", "May I put in some wax?"),
            ("You", "はい、お願いします。", "Hai, onegai shimasu.", "Yes, please."),
            ("Stylist", "お疲れさまでした。後ろはこんな感じです。", "Otsukaresama deshita. Ushiro wa konna kanji desu.", "All done. Here's how the back looks."),
            ("You", "ありがとうございます。すごく気に入りました。", "Arigatou gozaimasu. Sugoku ki ni irimashita.", "Thank you. I really love it."),
            ("Stylist", "よかったです。またお待ちしております。", "Yokatta desu. Mata omachi shite orimasu.", "I'm glad. We hope to see you again."),
        ],
    ),
]
