from app.services.listening_content.base import scenario

DAILY = "Daily life"
FRIENDS = "Friends & social"

SOCIAL_SCENARIOS = [
    scenario(
        "daily-routine",
        "Our daily routines",
        "Compare mornings, commutes, lunch, and evenings with a friend. Lots of time expressions and verbs.",
        setting="Café after class",
        category=DAILY,
        level="Beginner",
        lines=[
            ("Yuki", "コナーさんは、毎朝何時に起きますか。", "Konaa-san wa, maiasa nanji ni okimasu ka.", "Connor, what time do you get up every morning?"),
            ("You", "平日は六時半に起きます。", "Heijitsu wa rokuji han ni okimasu.", "On weekdays I get up at 6:30."),
            ("Yuki", "早いですね。起きてから、まず何をしますか。", "Hayai desu ne. Okite kara, mazu nani o shimasu ka.", "That's early. What do you do first after getting up?"),
            ("You", "まず水を一杯飲んで、それから軽くジョギングをします。", "Mazu mizu o ippai nonde, sore kara karuku jogingu o shimasu.", "First I drink a glass of water, then I go for a light jog."),
            ("Yuki", "毎日走るんですか。すごい！", "Mainichi hashirun desu ka. Sugoi!", "You run every day? Amazing!"),
            ("You", "雨の日は走りません。だいたい三十分ぐらい、公園の周りを走ります。", "Ame no hi wa hashirimasen. Daitai sanjuppun gurai, kouen no mawari o hashirimasu.", "Not on rainy days. I usually run around the park for about thirty minutes."),
            ("Yuki", "朝ごはんは何を食べますか。", "Asagohan wa nani o tabemasu ka.", "What do you eat for breakfast?"),
            ("You", "トーストと卵とコーヒーです。ゆきさんは？", "Toosuto to tamago to koohii desu. Yuki-san wa?", "Toast, eggs, and coffee. How about you, Yuki?"),
            ("Yuki", "私は和食が多いです。ご飯とみそ汁と納豆です。", "Watashi wa washoku ga ooi desu. Gohan to misoshiru to nattou desu.", "I usually have Japanese food. Rice, miso soup, and natto."),
            ("You", "納豆！私はまだ納豆が苦手です。においが強くて。", "Nattou! Watashi wa mada nattou ga nigate desu. Nioi ga tsuyokute.", "Natto! I still can't handle natto. The smell is so strong."),
            ("Yuki", "外国の人はよくそう言いますね。でも、体にとてもいいんですよ。", "Gaikoku no hito wa yoku sou iimasu ne. Demo, karada ni totemo iin desu yo.", "People from abroad often say that. But it's really good for you."),
            ("You", "会社には何で行きますか。", "Kaisha ni wa nan de ikimasu ka.", "How do you get to work?"),
            ("Yuki", "電車で行きます。家から会社まで、四十分ぐらいかかります。", "Densha de ikimasu. Ie kara kaisha made, yonjuppun gurai kakarimasu.", "By train. It takes about forty minutes from home to the office."),
            ("You", "電車は混んでいますか。", "Densha wa konde imasu ka.", "Is the train crowded?"),
            ("Yuki", "朝はすごく混んでいます。だから、いつも少し早い電車に乗ります。", "Asa wa sugoku konde imasu. Dakara, itsumo sukoshi hayai densha ni norimasu.", "It's packed in the morning. So I always take a slightly earlier train."),
            ("You", "私は自転車で通っています。十五分ぐらいです。", "Watashi wa jitensha de kayotte imasu. Juugofun gurai desu.", "I commute by bike. It's about fifteen minutes."),
            ("Yuki", "いいですね。お昼ごはんはどうしていますか。", "Ii desu ne. Ohirugohan wa dou shite imasu ka.", "Nice. What do you do for lunch?"),
            ("You", "会社の近くの定食屋で、よく食べます。安くておいしいんです。", "Kaisha no chikaku no teishokuya de, yoku tabemasu. Yasukute oishiin desu.", "I often eat at a set-meal place near work. It's cheap and tasty."),
            ("Yuki", "私はお弁当を作って、持って行きます。", "Watashi wa obentou o tsukutte, motte ikimasu.", "I make a bento and bring it."),
            ("You", "毎朝作るんですか。大変じゃないですか。", "Maiasa tsukurun desu ka. Taihen ja nai desu ka.", "You make one every morning? Isn't that hard?"),
            ("Yuki", "前の日の晩ごはんを多めに作って、それを入れるので、簡単ですよ。", "Mae no hi no bangohan o oome ni tsukutte, sore o ireru node, kantan desu yo.", "I make extra dinner the night before and pack that, so it's easy."),
            ("You", "なるほど、頭がいいですね。仕事は何時に終わりますか。", "Naruhodo, atama ga ii desu ne. Shigoto wa nanji ni owarimasu ka.", "I see, clever. What time do you finish work?"),
            ("Yuki", "だいたい六時です。でも、忙しい時は八時ぐらいまで残業します。", "Daitai rokuji desu. Demo, isogashii toki wa hachiji gurai made zangyou shimasu.", "Usually six. But when it's busy, I work overtime until about eight."),
            ("You", "家に帰ってから、何をしますか。", "Ie ni kaette kara, nani o shimasu ka.", "What do you do after you get home?"),
            ("Yuki", "晩ごはんを食べて、お風呂に入って、ドラマを見ます。", "Bangohan o tabete, ofuro ni haitte, dorama o mimasu.", "I eat dinner, take a bath, and watch dramas."),
            ("You", "私は寝る前に、日本語を三十分勉強します。", "Watashi wa neru mae ni, Nihongo o sanjuppun benkyou shimasu.", "I study Japanese for thirty minutes before bed."),
            ("Yuki", "えらいですね！だから上手なんですね。何時に寝ますか。", "Erai desu ne! Dakara jouzu nan desu ne. Nanji ni nemasu ka.", "Good for you! That's why you're so good. What time do you go to bed?"),
            ("You", "十一時ごろ寝ます。でも、ついスマホを見て、遅くなってしまいます。", "Juuichiji goro nemasu. Demo, tsui sumaho o mite, osoku natte shimaimasu.", "Around eleven. But I end up on my phone and stay up late."),
            ("Yuki", "それ、私もです。", "Sore, watashi mo desu.", "Same here."),
        ],
    ),
    scenario(
        "new-neighbor",
        "Meeting the neighbor",
        "Greet your new neighbor with a small gift and learn Japan's famously strict trash rules.",
        setting="Apartment hallway",
        category=DAILY,
        level="Intermediate",
        lines=[
            ("You", "すみません、隣の部屋に引っ越してきたコナーと申します。", "Sumimasen, tonari no heya ni hikkoshite kita Konaa to moushimasu.", "Excuse me, I'm Connor. I just moved in next door."),
            ("Tanaka", "ああ、どうも。田中です。", "Aa, doumo. Tanaka desu.", "Oh, hello. I'm Tanaka."),
            ("You", "これ、つまらないものですが、どうぞ。", "Kore, tsumaranai mono desu ga, douzo.", "This is just a little something, but please accept it."),
            ("Tanaka", "あら、ご丁寧にありがとうございます。タオルですね。", "Ara, goteinei ni arigatou gozaimasu. Taoru desu ne.", "Oh, how thoughtful. Thank you. Towels!"),
            ("You", "引っ越しの時、うるさくなかったですか。", "Hikkoshi no toki, urusaku nakatta desu ka.", "I hope I wasn't too noisy while moving in."),
            ("Tanaka", "いいえ、全然気になりませんでしたよ。", "Iie, zenzen ki ni narimasen deshita yo.", "Not at all. It didn't bother me."),
            ("Tanaka", "日本語がお上手ですね。日本は長いんですか。", "Nihongo ga ojouzu desu ne. Nihon wa nagain desu ka.", "Your Japanese is very good. Have you been in Japan long?"),
            ("You", "先月来たばかりです。前は大阪の語学学校にいました。", "Sengetsu kita bakari desu. Mae wa Oosaka no gogaku gakkou ni imashita.", "I only came last month. Before that, I was at a language school in Osaka."),
            ("Tanaka", "そうですか。何か分からないことがあったら、いつでも聞いてくださいね。", "Sou desu ka. Nanika wakaranai koto ga attara, itsu demo kiite kudasai ne.", "I see. If anything confuses you, feel free to ask me anytime."),
            ("You", "ありがとうございます。早速なんですが、ゴミの出し方を教えていただけますか。", "Arigatou gozaimasu. Sassoku nan desu ga, gomi no dashikata o oshiete itadakemasu ka.", "Thank you. Actually, right away, could you tell me how to put out the trash?"),
            ("Tanaka", "ええ、この地域は分別が厳しいので、気をつけてくださいね。", "Ee, kono chiiki wa bunbetsu ga kibishii node, ki o tsukete kudasai ne.", "Sure. Sorting is strict in this area, so be careful."),
            ("Tanaka", "燃えるゴミは、月曜日と木曜日です。", "Moeru gomi wa, getsuyoubi to mokuyoubi desu.", "Burnable trash goes out on Mondays and Thursdays."),
            ("You", "燃えるゴミは月曜日と木曜日ですね。生ゴミもですか。", "Moeru gomi wa getsuyoubi to mokuyoubi desu ne. Namagomi mo desu ka.", "Burnables on Monday and Thursday. Food waste too?"),
            ("Tanaka", "はい、生ゴミも燃えるゴミです。朝八時までに出してください。", "Hai, namagomi mo moeru gomi desu. Asa hachiji made ni dashite kudasai.", "Yes, food waste is burnable. Put it out by 8 a.m."),
            ("You", "ペットボトルや缶はどうですか。", "Petto botoru ya kan wa dou desu ka.", "What about plastic bottles and cans?"),
            ("Tanaka", "それは水曜日です。ペットボトルはキャップとラベルを外して、中を洗ってから出します。", "Sore wa suiyoubi desu. Petto botoru wa kyappu to raberu o hazushite, naka o aratte kara dashimasu.", "Those are Wednesday. Take the caps and labels off the bottles and rinse them before putting them out."),
            ("You", "キャップとラベルを外すんですね。けっこう細かいですね。", "Kyappu to raberu o hazusun desu ne. Kekkou komakai desu ne.", "Take off the caps and labels. That's pretty detailed."),
            ("Tanaka", "最初は大変ですけど、すぐ慣れますよ。分け方の表が、区役所のホームページにあります。", "Saisho wa taihen desu kedo, sugu naremasu yo. Wakekata no hyou ga, kuyakusho no hoomupeeji ni arimasu.", "It's tough at first, but you'll get used to it fast. There's a sorting chart on the ward office website."),
            ("You", "英語版もありますか。", "Eigoban mo arimasu ka.", "Is there an English version?"),
            ("Tanaka", "たしか、英語と中国語と韓国語のものがあったと思います。", "Tashika, eigo to Chuugokugo to Kankokugo no mono ga atta to omoimasu.", "I believe there are English, Chinese, and Korean versions."),
            ("You", "助かります。ゴミ置き場はどこですか。", "Tasukarimasu. Gomi okiba wa doko desu ka.", "That helps. Where is the garbage collection point?"),
            ("Tanaka", "一階の駐輪場の横です。ネットをかけないと、カラスに荒らされるので気をつけて。", "Ikkai no chuurinjou no yoko desu. Netto o kakenai to, karasu ni arasareru node ki o tsukete.", "Next to the bike parking on the ground floor. If you don't cover it with the net, the crows get into it."),
            ("You", "カラス！アメリカではあまり見ないので、びっくりしました。", "Karasu! Amerika de wa amari minai node, bikkuri shimashita.", "Crows! You don't see them much in America, so they surprised me."),
            ("Tanaka", "東京のカラスは、頭がいいですからね。", "Toukyou no karasu wa, atama ga ii desu kara ne.", "Tokyo crows are clever, you know."),
            ("You", "色々教えていただいて、ありがとうございました。", "Iroiro oshiete itadaite, arigatou gozaimashita.", "Thank you for explaining so much."),
            ("Tanaka", "いえいえ。これからよろしくお願いしますね。", "Ie ie. Kore kara yoroshiku onegai shimasu ne.", "Not at all. I look forward to being neighbors."),
            ("You", "こちらこそ、よろしくお願いします。", "Kochira koso, yoroshiku onegai shimasu.", "Likewise."),
        ],
    ),
    scenario(
        "first-meeting",
        "Meeting a new classmate",
        "Introduce yourself, talk about hometowns and why you study Japanese, and swap contact info.",
        setting="Language school",
        category=FRIENDS,
        level="Beginner",
        lines=[
            ("Yuki", "はじめまして。私はゆきです。", "Hajimemashite. Watashi wa Yuki desu.", "Nice to meet you. I'm Yuki."),
            ("You", "はじめまして。コナーです。よろしくお願いします。", "Hajimemashite. Konaa desu. Yoroshiku onegai shimasu.", "Nice to meet you. I'm Connor. Pleased to meet you."),
            ("Yuki", "よろしくお願いします。コナーさんは、どこから来ましたか。", "Yoroshiku onegai shimasu. Konaa-san wa, doko kara kimashita ka.", "Pleased to meet you. Where are you from, Connor?"),
            ("You", "アメリカから来ました。カリフォルニアです。", "Amerika kara kimashita. Kariforunia desu.", "I'm from America. California."),
            ("Yuki", "いいですね。カリフォルニアは暖かいですか。", "Ii desu ne. Kariforunia wa atatakai desu ka.", "Nice. Is California warm?"),
            ("You", "はい、一年中暖かいです。冬もあまり寒くないです。", "Hai, ichinenjuu atatakai desu. Fuyu mo amari samukunai desu.", "Yes, it's warm all year. Even winter isn't very cold."),
            ("Yuki", "うらやましいです。日本の冬は寒いですよ。", "Urayamashii desu. Nihon no fuyu wa samui desu yo.", "I'm jealous. Japanese winters are cold."),
            ("You", "ゆきさんは、東京の人ですか。", "Yuki-san wa, Toukyou no hito desu ka.", "Are you from Tokyo, Yuki?"),
            ("Yuki", "いいえ、北海道の札幌出身です。", "Iie, Hokkaidou no Sapporo shusshin desu.", "No, I'm from Sapporo in Hokkaido."),
            ("You", "北海道！雪がたくさん降りますよね。", "Hokkaidou! Yuki ga takusan furimasu yo ne.", "Hokkaido! It snows a lot there, right?"),
            ("Yuki", "はい。名前も「雪」なんです。冬に生まれたので。", "Hai. Namae mo \"yuki\" nan desu. Fuyu ni umareta node.", "Yes. My name means \"snow\" too, because I was born in winter."),
            ("You", "すてきな名前ですね。", "Suteki na namae desu ne.", "What a lovely name."),
            ("Yuki", "ありがとうございます。コナーさんは、どうして日本語を勉強していますか。", "Arigatou gozaimasu. Konaa-san wa, doushite Nihongo o benkyou shite imasu ka.", "Thank you. Why are you studying Japanese, Connor?"),
            ("You", "日本のアニメと料理が好きだからです。いつか日本で働きたいです。", "Nihon no anime to ryouri ga suki da kara desu. Itsuka Nihon de hatarakitai desu.", "Because I love Japanese anime and food. I want to work in Japan someday."),
            ("Yuki", "そうですか。どのくらい勉強していますか。", "Sou desu ka. Dono kurai benkyou shite imasu ka.", "I see. How long have you been studying?"),
            ("You", "まだ一年ぐらいです。ひらがなとカタカナは読めますが、漢字は難しいです。", "Mada ichinen gurai desu. Hiragana to katakana wa yomemasu ga, kanji wa muzukashii desu.", "Only about a year. I can read hiragana and katakana, but kanji is hard."),
            ("Yuki", "一年でそんなに話せるなんて、すごいですね。", "Ichinen de sonna ni hanaseru nante, sugoi desu ne.", "Speaking this well after one year is amazing."),
            ("You", "いえいえ、まだまだです。ゆきさんは英語を話しますか。", "Ie ie, madamada desu. Yuki-san wa eigo o hanashimasu ka.", "Oh no, I've got a long way to go. Do you speak English, Yuki?"),
            ("Yuki", "少しだけ話します。でも、恥ずかしいです。", "Sukoshi dake hanashimasu. Demo, hazukashii desu.", "Just a little. But I get shy."),
            ("You", "じゃあ、一緒に練習しませんか。私は日本語、ゆきさんは英語。", "Jaa, issho ni renshuu shimasen ka. Watashi wa Nihongo, Yuki-san wa eigo.", "Then why don't we practice together? Japanese for me, English for you."),
            ("Yuki", "いいアイデアですね！ぜひお願いします。", "Ii aidea desu ne! Zehi onegai shimasu.", "Great idea! I'd love to."),
            ("You", "連絡先を交換してもいいですか。", "Renrakusaki o koukan shite mo ii desu ka.", "Can we exchange contact info?"),
            ("Yuki", "はい、ラインでいいですか。", "Hai, Rain de ii desu ka.", "Sure, is LINE okay?"),
            ("You", "はい、大丈夫です。これが私のキューアールコードです。", "Hai, daijoubu desu. Kore ga watashi no kyuuaaru koodo desu.", "Yes, that's fine. Here's my QR code."),
            ("Yuki", "追加しました。スタンプを送りますね。", "Tsuika shimashita. Sutanpu o okurimasu ne.", "I added you. I'll send you a sticker."),
            ("You", "届きました！かわいいスタンプですね。", "Todokimashita! Kawaii sutanpu desu ne.", "Got it! What a cute sticker."),
            ("Yuki", "じゃあ、また授業で会いましょう。", "Jaa, mata jugyou de aimashou.", "Well, see you in class."),
            ("You", "はい、また来週。", "Hai, mata raishuu.", "Yes, see you next week."),
        ],
    ),
    scenario(
        "talking-about-family",
        "Talking about family",
        "Look at family photos together: siblings, parents' jobs, nieces and nephews, and keeping in touch.",
        setting="Yuki's apartment",
        category=FRIENDS,
        level="Elementary",
        lines=[
            ("Yuki", "これ、コナーさんの家族の写真ですか。", "Kore, Konaa-san no kazoku no shashin desu ka.", "Is this a photo of your family, Connor?"),
            ("You", "はい、去年のクリスマスに撮りました。", "Hai, kyonen no kurisumasu ni torimashita.", "Yes, I took it last Christmas."),
            ("Yuki", "何人家族ですか。", "Nannin kazoku desu ka.", "How many people are in your family?"),
            ("You", "五人家族です。父と母と、姉と弟と私です。", "Gonin kazoku desu. Chichi to haha to, ane to otouto to watashi desu.", "Five. My dad, my mom, my older sister, my younger brother, and me."),
            ("Yuki", "この背の高い人は、お父さんですか。", "Kono se no takai hito wa, otousan desu ka.", "Is this tall person your father?"),
            ("You", "いいえ、それは弟です。まだ十九歳ですが、家族で一番背が高いんです。", "Iie, sore wa otouto desu. Mada juukyuu sai desu ga, kazoku de ichiban se ga takain desu.", "No, that's my little brother. He's only nineteen, but he's the tallest in the family."),
            ("Yuki", "へえ！弟さんは学生ですか。", "Hee! Otouto-san wa gakusei desu ka.", "Wow! Is your brother a student?"),
            ("You", "はい、大学生です。バスケットボールをしています。", "Hai, daigakusei desu. Basukettobooru o shite imasu.", "Yes, he's in university. He plays basketball."),
            ("Yuki", "だから背が高いんですね。お姉さんは？", "Dakara se ga takain desu ne. Oneesan wa?", "That's why he's so tall. And your sister?"),
            ("You", "姉は看護師で、シアトルに住んでいます。結婚していて、子どもが二人います。", "Ane wa kangoshi de, Shiatoru ni sunde imasu. Kekkon shite ite, kodomo ga futari imasu.", "My sister is a nurse and lives in Seattle. She's married with two kids."),
            ("Yuki", "じゃあ、コナーさんはおじさんなんですね。", "Jaa, Konaa-san wa ojisan nan desu ne.", "So you're an uncle!"),
            ("You", "そうなんです。めいとおいがいます。二人とも、すごくかわいいです。", "Sou nan desu. Mei to oi ga imasu. Futari tomo, sugoku kawaii desu.", "That's right. I have a niece and a nephew. They're both super cute."),
            ("Yuki", "ご両親は、何をしていますか。", "Goryoushin wa, nani o shite imasu ka.", "What do your parents do?"),
            ("You", "父は高校の先生で、母は小さいパン屋をやっています。", "Chichi wa koukou no sensei de, haha wa chiisai pan'ya o yatte imasu.", "My father is a high school teacher, and my mother runs a small bakery."),
            ("Yuki", "パン屋さん！いいですね。毎日おいしいパンが食べられますね。", "Pan'ya-san! Ii desu ne. Mainichi oishii pan ga taberaremasu ne.", "A bakery! How nice. You can have delicious bread every day."),
            ("You", "子どものころは毎朝食べていました。今は日本にいるので、ちょっと寂しいです。", "Kodomo no koro wa maiasa tabete imashita. Ima wa Nihon ni iru node, chotto sabishii desu.", "I ate it every morning as a kid. Now that I'm in Japan, I miss it a bit."),
            ("Yuki", "家族とは、よく話しますか。", "Kazoku to wa, yoku hanashimasu ka.", "Do you talk with your family often?"),
            ("You", "週に一回、ビデオ通話をします。時差があるので、時間を合わせるのが大変です。", "Shuu ni ikkai, bideo tsuuwa o shimasu. Jisa ga aru node, jikan o awaseru no ga taihen desu.", "We video call once a week. With the time difference, finding a time is tough."),
            ("You", "ゆきさんは、兄弟がいますか。", "Yuki-san wa, kyoudai ga imasu ka.", "Do you have any siblings, Yuki?"),
            ("Yuki", "私は一人っ子なんです。", "Watashi wa hitorikko nan desu.", "I'm an only child."),
            ("You", "そうなんですか。寂しくなかったですか。", "Sou nan desu ka. Sabishiku nakatta desu ka.", "Really? Weren't you lonely?"),
            ("Yuki", "小さいころは少し。でも、いとこがたくさんいて、よく一緒に遊んでいました。", "Chiisai koro wa sukoshi. Demo, itoko ga takusan ite, yoku issho ni asonde imashita.", "A little when I was small. But I have lots of cousins, and we played together a lot."),
            ("You", "ご両親は、札幌に住んでいるんですか。", "Goryoushin wa, Sapporo ni sunde irun desu ka.", "Do your parents live in Sapporo?"),
            ("Yuki", "はい。父は会社員で、母は料理教室の先生です。", "Hai. Chichi wa kaishain de, haha wa ryouri kyoushitsu no sensei desu.", "Yes. My father is an office worker, and my mother teaches cooking classes."),
            ("You", "料理教室！いつか日本料理を教えてもらいたいです。", "Ryouri kyoushitsu! Itsuka Nihon ryouri o oshiete moraitai desu.", "Cooking classes! I'd love to learn Japanese cooking from her someday."),
            ("Yuki", "母に言ったら、きっと喜びますよ。冬休みに札幌に来ませんか。", "Haha ni ittara, kitto yorokobimasu yo. Fuyuyasumi ni Sapporo ni kimasen ka.", "My mom would be thrilled if I told her. Why not come to Sapporo over winter break?"),
            ("You", "本当ですか。雪まつりを見てみたいです！", "Hontou desu ka. Yuki matsuri o mite mitai desu!", "Really? I'd love to see the Snow Festival!"),
            ("Yuki", "雪まつりは二月なので、ちょうどいいですね。", "Yuki matsuri wa nigatsu na node, choudo ii desu ne.", "The Snow Festival is in February, so that's perfect timing."),
        ],
    ),
    scenario(
        "hobbies",
        "Talking about hobbies",
        "Swap hobbies with a coworker: photography, soccer, and cooking, then make plans to cook together.",
        setting="Office break room",
        category=FRIENDS,
        level="Elementary",
        lines=[
            ("Kenta", "コナーさん、週末は何をしていますか。", "Konaa-san, shuumatsu wa nani o shite imasu ka.", "Connor, what do you do on weekends?"),
            ("You", "よく写真を撮りに出かけます。カメラが趣味なんです。", "Yoku shashin o tori ni dekakemasu. Kamera ga shumi nan desu.", "I often go out to take photos. Photography is my hobby."),
            ("Kenta", "へえ、どんな写真を撮るんですか。", "Hee, donna shashin o torun desu ka.", "Oh, what kind of photos do you take?"),
            ("You", "町の風景が多いです。特に、夜の東京が好きです。", "Machi no fuukei ga ooi desu. Toku ni, yoru no Toukyou ga suki desu.", "Mostly cityscapes. I especially love Tokyo at night."),
            ("Kenta", "見てみたいです。", "Mite mitai desu.", "I'd love to see them."),
            ("You", "これは先週、渋谷で撮りました。", "Kore wa senshuu, Shibuya de torimashita.", "I took this one in Shibuya last week."),
            ("Kenta", "きれい！プロみたいですね。", "Kirei! Puro mitai desu ne.", "Beautiful! You're like a pro."),
            ("You", "ありがとうございます。ケンタさんの趣味は何ですか。", "Arigatou gozaimasu. Kenta-san no shumi wa nan desu ka.", "Thanks. What are your hobbies, Kenta?"),
            ("Kenta", "僕は料理とサッカーです。", "Boku wa ryouri to sakkaa desu.", "Cooking and soccer."),
            ("You", "サッカーは、するほうですか、見るほうですか。", "Sakkaa wa, suru hou desu ka, miru hou desu ka.", "Do you play soccer or watch it?"),
            ("Kenta", "両方です。毎週日曜日に、会社のチームで試合をしています。", "Ryouhou desu. Maishuu nichiyoubi ni, kaisha no chiimu de shiai o shite imasu.", "Both. Every Sunday I play matches with the company team."),
            ("You", "すごいですね。ポジションはどこですか。", "Sugoi desu ne. Pojishon wa doko desu ka.", "Cool. What position do you play?"),
            ("Kenta", "ディフェンダーです。あまり上手じゃないですけどね。", "Difendaa desu. Amari jouzu ja nai desu kedo ne.", "Defender. I'm not very good, though."),
            ("You", "料理は、どんなものを作りますか。", "Ryouri wa, donna mono o tsukurimasu ka.", "What kind of food do you cook?"),
            ("Kenta", "最近は、イタリア料理にはまっています。パスタを手作りしているんです。", "Saikin wa, Itaria ryouri ni hamatte imasu. Pasuta o tezukuri shite irun desu.", "Lately I'm hooked on Italian food. I make pasta from scratch."),
            ("You", "パスタを手作り？難しくないですか。", "Pasuta o tezukuri? Muzukashiku nai desu ka.", "Homemade pasta? Isn't that hard?"),
            ("Kenta", "最初は難しかったけど、慣れたら楽しいですよ。", "Saisho wa muzukashikatta kedo, naretara tanoshii desu yo.", "It was hard at first, but once you get the hang of it, it's fun."),
            ("You", "私も料理を習いたいです。日本料理は全然作れないんです。", "Watashi mo ryouri o naraitai desu. Nihon ryouri wa zenzen tsukurenain desu.", "I want to learn to cook too. I can't make Japanese food at all."),
            ("Kenta", "じゃあ、今度うちで一緒に作りませんか。肉じゃがなら簡単ですよ。", "Jaa, kondo uchi de issho ni tsukurimasen ka. Nikujaga nara kantan desu yo.", "Then why don't we cook together at my place sometime? Nikujaga is easy."),
            ("You", "肉じゃがって何ですか。", "Nikujaga tte nan desu ka.", "What's nikujaga?"),
            ("Kenta", "肉とじゃがいもを、甘い醤油で煮た料理です。日本の家庭料理の代表ですね。", "Niku to jagaimo o, amai shouyu de nita ryouri desu. Nihon no katei ryouri no daihyou desu ne.", "Meat and potatoes simmered in sweet soy sauce. It's classic Japanese home cooking."),
            ("You", "おいしそう！ぜひ作りたいです。", "Oishisou! Zehi tsukuritai desu.", "Sounds delicious! I'd love to make it."),
            ("Kenta", "そのかわり、写真の撮り方を教えてください。", "Sono kawari, shashin no torikata o oshiete kudasai.", "In exchange, teach me how to take photos."),
            ("You", "もちろんです。スマホでもきれいに撮れるコツがあるんですよ。", "Mochiron desu. Sumaho demo kirei ni toreru kotsu ga arun desu yo.", "Of course. There are tricks for great shots even on a phone."),
            ("Kenta", "楽しみです。いつがいいですか。", "Tanoshimi desu. Itsu ga ii desu ka.", "I'm looking forward to it. When works for you?"),
            ("You", "来週の土曜日はどうですか。", "Raishuu no doyoubi wa dou desu ka.", "How about next Saturday?"),
            ("Kenta", "土曜日の午後なら大丈夫です。材料は僕が買っておきますね。", "Doyoubi no gogo nara daijoubu desu. Zairyou wa boku ga katte okimasu ne.", "Saturday afternoon works. I'll pick up the ingredients."),
            ("You", "じゃあ、私は飲み物とデザートを持って行きます。", "Jaa, watashi wa nomimono to dezaato o motte ikimasu.", "Then I'll bring drinks and dessert."),
            ("Kenta", "いいですね。決まりですね！", "Ii desu ne. Kimari desu ne!", "Great. It's a plan!"),
        ],
    ),
    scenario(
        "language-exchange",
        "Language exchange: asking what words mean",
        "Talk about a trip to Hakone and practice asking someone to repeat, slow down, and explain new words.",
        setting="Language exchange café",
        category=FRIENDS,
        level="Elementary",
        lines=[
            ("Mai", "こんにちは。今日は何について話しましょうか。", "Konnichiwa. Kyou wa nani ni tsuite hanashimashou ka.", "Hello. What shall we talk about today?"),
            ("You", "最近の休みについて話したいです。", "Saikin no yasumi ni tsuite hanashitai desu.", "I'd like to talk about my recent vacation."),
            ("Mai", "いいですね。どこかに行きましたか。", "Ii desu ne. Dokoka ni ikimashita ka.", "Great. Did you go somewhere?"),
            ("You", "はい、先週、友達と箱根に行きました。", "Hai, senshuu, tomodachi to Hakone ni ikimashita.", "Yes, last week I went to Hakone with a friend."),
            ("Mai", "箱根ですか。紅葉シーズンだから、混んでいたんじゃないですか。", "Hakone desu ka. Kouyou shiizun dakara, konde itan ja nai desu ka.", "Hakone? It's autumn-leaves season, so wasn't it crowded?"),
            ("You", "すみません、もう一度ゆっくり言ってもらえますか。", "Sumimasen, mou ichido yukkuri itte moraemasu ka.", "Sorry, could you say that again slowly?"),
            ("Mai", "もちろん。紅葉の、シーズンなので、人が、多かったですか。", "Mochiron. Kouyou no, shiizun na node, hito ga, ookatta desu ka.", "Of course. Since it's the autumn-leaves season, were there lots of people?"),
            ("You", "ああ、分かりました。はい、すごく混んでいました。", "Aa, wakarimashita. Hai, sugoku konde imashita.", "Ah, I understand. Yes, it was really crowded."),
            ("You", "「こうよう」は、どういう意味ですか。", "\"Kouyou\" wa, dou iu imi desu ka.", "What does \"kouyou\" mean?"),
            ("Mai", "秋に、葉っぱが赤や黄色になることです。英語で何と言いますか。", "Aki ni, happa ga aka ya kiiro ni naru koto desu. Eigo de nan to iimasu ka.", "It's when leaves turn red and yellow in autumn. How do you say it in English?"),
            ("You", "英語では「オータム・リーブズ」と言います。", "Eigo de wa \"ootamu riibuzu\" to iimasu.", "In English we say \"autumn leaves.\""),
            ("Mai", "なるほど。箱根では何をしましたか。", "Naruhodo. Hakone de wa nani o shimashita ka.", "I see. What did you do in Hakone?"),
            ("You", "温泉に入って、それから芦ノ湖で船に乗りました。", "Onsen ni haitte, sore kara Ashinoko de fune ni norimashita.", "We went to a hot spring, then took a boat on Lake Ashi."),
            ("Mai", "富士山は見えましたか。", "Fujisan wa miemashita ka.", "Could you see Mount Fuji?"),
            ("You", "残念ながら、曇っていて見えませんでした。", "Zannen nagara, kumotte ite miemasen deshita.", "Unfortunately it was cloudy, so we couldn't."),
            ("Mai", "それは惜しかったですね。黒たまごは食べましたか。", "Sore wa oshikatta desu ne. Kurotamago wa tabemashita ka.", "So close! Did you eat a black egg?"),
            ("You", "すみません、「おしかった」はどういう意味ですか。", "Sumimasen, \"oshikatta\" wa dou iu imi desu ka.", "Sorry, what does \"oshikatta\" mean?"),
            ("Mai", "「もう少しだったのに、残念」という意味です。", "\"Mou sukoshi datta noni, zannen\" to iu imi desu.", "It means \"it was so close, what a pity.\""),
            ("You", "なるほど。メモしてもいいですか。", "Naruhodo. Memo shite mo ii desu ka.", "I see. May I write that down?"),
            ("Mai", "どうぞ。漢字で書くと「惜しい」です。", "Douzo. Kanji de kaku to \"oshii\" desu.", "Go ahead. In kanji, it's written 惜しい."),
            ("You", "黒たまごは食べました。一つ食べると、七年長生きできると聞きました。", "Kurotamago wa tabemashita. Hitotsu taberu to, nananen nagaiki dekiru to kikimashita.", "I did eat a black egg. I heard each one adds seven years to your life."),
            ("Mai", "そうそう。いくつ食べましたか。", "Sou sou. Ikutsu tabemashita ka.", "That's right. How many did you eat?"),
            ("You", "三つ食べました。だから、二十一年長生きします！", "Mittsu tabemashita. Dakara, nijuuichinen nagaiki shimasu!", "Three. So I'll live twenty-one years longer!"),
            ("Mai", "あはは、上手ですね。じゃあ、ここからは英語で話しましょうか。", "Ahaha, jouzu desu ne. Jaa, koko kara wa eigo de hanashimashou ka.", "Ha ha, nicely put. Shall we switch to English from here?"),
            ("You", "はい。でもその前に、今日の新しい言葉を確認してもいいですか。", "Hai. Demo sono mae ni, kyou no atarashii kotoba o kakunin shite mo ii desu ka.", "Sure. But first, can I review today's new words?"),
            ("Mai", "いいですよ。どうぞ。", "Ii desu yo. Douzo.", "Of course. Go ahead."),
            ("You", "「紅葉」「惜しい」「長生き」。合っていますか。", "\"Kouyou\", \"oshii\", \"nagaiki\". Atte imasu ka.", "Kouyou, oshii, nagaiki. Did I get them right?"),
            ("Mai", "完璧です！発音もとてもきれいですよ。", "Kanpeki desu! Hatsuon mo totemo kirei desu yo.", "Perfect! Your pronunciation is great too."),
        ],
    ),
    scenario(
        "weekend-plans",
        "Planning a day trip",
        "Plan a Saturday in Kamakura with a friend: meeting time, which exit, lunch, and the Enoden. Casual speech.",
        setting="Text-style chat with a friend",
        category=FRIENDS,
        level="Elementary",
        lines=[
            ("Kenta", "ねえ、今週末ひま？", "Nee, konshuumatsu hima?", "Hey, are you free this weekend?"),
            ("You", "土曜日はひまだよ。日曜日は、午前中だけバイトがある。", "Doyoubi wa hima da yo. Nichiyoubi wa, gozenchuu dake baito ga aru.", "I'm free Saturday. Sunday I work in the morning."),
            ("Kenta", "じゃあ、土曜日に鎌倉に行かない？", "Jaa, doyoubi ni Kamakura ni ikanai?", "Then want to go to Kamakura on Saturday?"),
            ("You", "鎌倉！行きたかったんだ。大仏があるところだよね。", "Kamakura! Ikitakattan da. Daibutsu ga aru tokoro da yo ne.", "Kamakura! I've wanted to go. That's where the Great Buddha is, right?"),
            ("Kenta", "そうそう。海も近いし、お寺もたくさんあるよ。", "Sou sou. Umi mo chikai shi, otera mo takusan aru yo.", "Yep. It's close to the sea, and there are lots of temples."),
            ("You", "どうやって行くの？", "Dou yatte iku no?", "How do we get there?"),
            ("Kenta", "東京駅から横須賀線で一時間ぐらい。乗り換えなしで行けるよ。", "Toukyou eki kara Yokosukasen de ichijikan gurai. Norikae nashi de ikeru yo.", "About an hour on the Yokosuka Line from Tokyo Station. No transfers."),
            ("You", "何時に待ち合わせする？", "Nanji ni machiawase suru?", "What time should we meet?"),
            ("Kenta", "早めに行ったほうが空いてるから、八時半に東京駅はどう？", "Hayame ni itta hou ga suiteru kara, hachiji han ni Toukyou eki wa dou?", "It's less crowded if we go early, so how about 8:30 at Tokyo Station?"),
            ("You", "八時半か。ちょっと早いけど、頑張る。", "Hachiji han ka. Chotto hayai kedo, ganbaru.", "8:30, huh. A bit early, but I'll manage."),
            ("Kenta", "改札の前で待ってるね。", "Kaisatsu no mae de matteru ne.", "I'll wait in front of the ticket gate."),
            ("You", "どの改札？東京駅は改札がたくさんあるから、迷いそう。", "Dono kaisatsu? Toukyou eki wa kaisatsu ga takusan aru kara, mayoisou.", "Which gate? Tokyo Station has so many, I might get lost."),
            ("Kenta", "確かに。じゃあ、丸の内北口にしよう。地図を送るね。", "Tashika ni. Jaa, Marunouchi kitaguchi ni shiyou. Chizu o okuru ne.", "Good point. Let's do the Marunouchi North Exit. I'll send you a map."),
            ("You", "ありがとう。お昼はどうする？", "Arigatou. Ohiru wa dou suru?", "Thanks. What about lunch?"),
            ("Kenta", "鎌倉は、しらす丼が有名なんだ。食べたことある？", "Kamakura wa, shirasudon ga yuumei nan da. Tabeta koto aru?", "Kamakura is famous for shirasu rice bowls. Have you had one?"),
            ("You", "ないなあ。しらすって何？", "Nai naa. Shirasu tte nani?", "Never. What's shirasu?"),
            ("Kenta", "小さい白い魚。ご飯の上にたくさんのせて食べるんだ。", "Chiisai shiroi sakana. Gohan no ue ni takusan nosete taberun da.", "Tiny white fish. You pile lots of them on rice."),
            ("You", "面白そう。食べてみたい。", "Omoshirosou. Tabete mitai.", "Sounds interesting. I want to try it."),
            ("Kenta", "天気予報、見た？土曜日は晴れるみたいだよ。", "Tenki yohou, mita? Doyoubi wa hareru mitai da yo.", "Did you check the forecast? Looks like Saturday will be sunny."),
            ("You", "よかった。じゃあ、海にも行こうよ。夕日が見たいな。", "Yokatta. Jaa, umi ni mo ikou yo. Yuuhi ga mitai na.", "Great. Then let's hit the beach too. I want to see the sunset."),
            ("Kenta", "いいね。江ノ島まで行けば、夕日がすごくきれいだよ。", "Ii ne. Enoshima made ikeba, yuuhi ga sugoku kirei da yo.", "Nice. If we go out to Enoshima, the sunset is gorgeous."),
            ("You", "江ノ電に乗れる？前から乗ってみたかったんだ。", "Enoden ni noreru? Mae kara notte mitakattan da.", "Can we ride the Enoden? I've always wanted to."),
            ("Kenta", "もちろん。江ノ電で江ノ島まで行こう。", "Mochiron. Enoden de Enoshima made ikou.", "Of course. Let's take the Enoden to Enoshima."),
            ("You", "楽しみ！何か持って行ったほうがいいものある？", "Tanoshimi! Nanika motte itta hou ga ii mono aru?", "Can't wait! Anything I should bring?"),
            ("Kenta", "たくさん歩くから、歩きやすい靴で来てね。あと、日焼け止めもね。", "Takusan aruku kara, arukiyasui kutsu de kite ne. Ato, hiyakedome mo ne.", "We'll walk a lot, so wear comfy shoes. And sunscreen."),
            ("You", "了解。じゃあ、土曜日の八時半に、丸の内北口ね。", "Ryoukai. Jaa, doyoubi no hachiji han ni, Marunouchi kitaguchi ne.", "Got it. Saturday, 8:30, Marunouchi North Exit."),
            ("Kenta", "うん。遅れないでよ！", "Un. Okurenaide yo!", "Yep. Don't be late!"),
            ("You", "大丈夫、目覚ましを三つかけるから。", "Daijoubu, mezamashi o mittsu kakeru kara.", "Don't worry, I'll set three alarms."),
        ],
    ),
]
