from app.services.listening_content.base import scenario

CATEGORY = "Travel in Japan"

TRAVEL_SCENARIOS = [
    scenario(
        "airport-arrival",
        "Arriving at the airport",
        "Get through immigration and customs: purpose of visit, length of stay, and what's in your bag.",
        setting="Narita Airport",
        category=CATEGORY,
        level="Beginner",
        lines=[
            ("Officer", "次の方、どうぞ。", "Tsugi no kata, douzo.", "Next person, please."),
            ("You", "こんにちは。よろしくお願いします。", "Konnichiwa. Yoroshiku onegai shimasu.", "Hello. Thank you in advance."),
            ("Officer", "パスポートを見せてください。", "Pasupooto o misete kudasai.", "Please show me your passport."),
            ("You", "はい、どうぞ。", "Hai, douzo.", "Yes, here you are."),
            ("Officer", "日本は初めてですか。", "Nihon wa hajimete desu ka.", "Is this your first time in Japan?"),
            ("You", "いいえ、二回目です。", "Iie, nikaime desu.", "No, it's my second time."),
            ("Officer", "今回の目的は何ですか。", "Konkai no mokuteki wa nan desu ka.", "What is the purpose of this visit?"),
            ("You", "観光です。", "Kankou desu.", "Sightseeing."),
            ("Officer", "どのくらい滞在しますか。", "Dono kurai taizai shimasu ka.", "How long will you stay?"),
            ("You", "二週間です。", "Nishuukan desu.", "Two weeks."),
            ("Officer", "どこに泊まりますか。", "Doko ni tomarimasu ka.", "Where will you stay?"),
            ("You", "東京のホテルに泊まります。そのあと、京都にも行きます。", "Toukyou no hoteru ni tomarimasu. Sono ato, Kyouto ni mo ikimasu.", "I'll stay at a hotel in Tokyo. After that, I'll also go to Kyoto."),
            ("Officer", "ホテルの名前は分かりますか。", "Hoteru no namae wa wakarimasu ka.", "Do you know the name of the hotel?"),
            ("You", "はい、新宿のさくらホテルです。", "Hai, Shinjuku no Sakura Hoteru desu.", "Yes, it's the Sakura Hotel in Shinjuku."),
            ("Officer", "帰りの航空券はありますか。", "Kaeri no koukuuken wa arimasu ka.", "Do you have a return ticket?"),
            ("You", "はい、あります。携帯で見せてもいいですか。", "Hai, arimasu. Keitai de misete mo ii desu ka.", "Yes, I do. May I show it on my phone?"),
            ("Officer", "はい、大丈夫です。", "Hai, daijoubu desu.", "Yes, that's fine."),
            ("Officer", "では、両手の人差し指をここに置いてください。", "Dewa, ryoute no hitosashiyubi o koko ni oite kudasai.", "Now, please place both index fingers here."),
            ("You", "こうですか。", "Kou desu ka.", "Like this?"),
            ("Officer", "はい、そうです。次にカメラを見てください。", "Hai, sou desu. Tsugi ni kamera o mite kudasai.", "Yes, that's right. Next, please look at the camera."),
            ("Officer", "はい、終わりました。よい旅を。", "Hai, owarimashita. Yoi tabi o.", "All done. Have a good trip."),
            ("You", "ありがとうございます。", "Arigatou gozaimasu.", "Thank you."),
            ("Customs", "申告するものはありますか。", "Shinkoku suru mono wa arimasu ka.", "Do you have anything to declare?"),
            ("You", "いいえ、ありません。", "Iie, arimasen.", "No, I don't."),
            ("Customs", "荷物はこのスーツケースだけですか。", "Nimotsu wa kono suutsukeesu dake desu ka.", "Is this suitcase your only luggage?"),
            ("You", "はい、それとこのリュックです。", "Hai, sore to kono ryukku desu.", "Yes, and this backpack."),
            ("Customs", "食べ物や果物は入っていますか。", "Tabemono ya kudamono wa haitte imasu ka.", "Is there any food or fruit inside?"),
            ("You", "お菓子が少しだけ入っています。", "Okashi ga sukoshi dake haitte imasu.", "Just a few snacks."),
            ("Customs", "お菓子なら大丈夫です。どうぞ、お進みください。", "Okashi nara daijoubu desu. Douzo, osusumi kudasai.", "Snacks are fine. Please go ahead."),
            ("You", "どうもありがとうございました。", "Doumo arigatou gozaimashita.", "Thank you very much."),
        ],
    ),
    scenario(
        "asking-directions",
        "Asking for directions",
        "You're heading the wrong way. Ask for help, follow the directions, and ask them to repeat slowly.",
        setting="Street in Tokyo",
        category=CATEGORY,
        level="Beginner",
        lines=[
            ("You", "すみません、ちょっと道を聞いてもいいですか。", "Sumimasen, chotto michi o kiite mo ii desu ka.", "Excuse me, may I ask for directions?"),
            ("Local", "はい、いいですよ。", "Hai, ii desu yo.", "Sure."),
            ("You", "東京駅に行きたいんですが、この道で合っていますか。", "Toukyou eki ni ikitain desu ga, kono michi de atte imasu ka.", "I want to go to Tokyo Station. Am I on the right road?"),
            ("Local", "あ、反対ですね。東京駅はあっちの方向です。", "A, hantai desu ne. Toukyou eki wa acchi no houkou desu.", "Oh, it's the other way. Tokyo Station is in that direction."),
            ("You", "そうですか。歩いて行けますか。", "Sou desu ka. Aruite ikemasu ka.", "Really? Can I walk there?"),
            ("Local", "歩くと十五分ぐらいかかりますね。", "Aruku to juugofun gurai kakarimasu ne.", "Walking takes about fifteen minutes."),
            ("You", "大丈夫です。歩くのが好きなので。", "Daijoubu desu. Aruku no ga suki na node.", "That's fine. I like walking."),
            ("Local", "じゃあ、この道をまっすぐ行って、二つ目の信号を右に曲がってください。", "Jaa, kono michi o massugu itte, futatsume no shingou o migi ni magatte kudasai.", "Then go straight along this road and turn right at the second traffic light."),
            ("You", "二つ目の信号を右ですね。", "Futatsume no shingou o migi desu ne.", "Right at the second light."),
            ("Local", "はい。そうすると、大きい本屋が見えます。", "Hai. Sou suru to, ookii hon'ya ga miemasu.", "Yes. Then you'll see a big bookstore."),
            ("You", "本屋ですね。", "Hon'ya desu ne.", "A bookstore."),
            ("Local", "その本屋の前の横断歩道を渡って、まっすぐ行くと、駅が見えますよ。", "Sono hon'ya no mae no oudanhodou o watatte, massugu iku to, eki ga miemasu yo.", "Cross the crosswalk in front of that bookstore, go straight, and you'll see the station."),
            ("You", "すみません、もう一度ゆっくり言っていただけますか。", "Sumimasen, mou ichido yukkuri itte itadakemasu ka.", "Sorry, could you say that once more, slowly?"),
            ("Local", "もちろん。まっすぐ行って、二つ目の信号を右。本屋の前で道を渡って、まっすぐです。", "Mochiron. Massugu itte, futatsume no shingou o migi. Hon'ya no mae de michi o watatte, massugu desu.", "Of course. Go straight, right at the second light. Cross the road in front of the bookstore, then straight on."),
            ("You", "よく分かりました。地図で見せてもらえますか。", "Yoku wakarimashita. Chizu de misete moraemasu ka.", "Got it. Could you show me on the map?"),
            ("Local", "いいですよ。今ここにいて、駅はここです。", "Ii desu yo. Ima koko ni ite, eki wa koko desu.", "Sure. We're here now, and the station is here."),
            ("You", "近くにトイレはありますか。", "Chikaku ni toire wa arimasu ka.", "Is there a restroom nearby?"),
            ("Local", "本屋の中にありますよ。きれいなので、おすすめです。", "Hon'ya no naka ni arimasu yo. Kirei na node, osusume desu.", "There's one inside the bookstore. It's clean, so I recommend it."),
            ("You", "助かります。", "Tasukarimasu.", "That's a big help."),
            ("Local", "どちらから来たんですか。", "Dochira kara kitan desu ka.", "Where are you from?"),
            ("You", "アメリカから来ました。", "Amerika kara kimashita.", "I'm from America."),
            ("Local", "そうなんですか。日本の旅行はどうですか。", "Sou nan desu ka. Nihon no ryokou wa dou desu ka.", "Oh really? How is your trip to Japan?"),
            ("You", "すごく楽しいです。みんな親切です。", "Sugoku tanoshii desu. Minna shinsetsu desu.", "It's really fun. Everyone is kind."),
            ("Local", "よかったです。じゃあ、気をつけて。", "Yokatta desu. Jaa, ki o tsukete.", "I'm glad. Well, take care."),
            ("You", "本当にありがとうございました。", "Hontou ni arigatou gozaimashita.", "Thank you so much."),
        ],
    ),
    scenario(
        "train-to-the-city",
        "Getting into the city",
        "Buy a limited express ticket from the airport, pick a seat, and pick up an IC card.",
        setting="Airport train station",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("You", "すみません、ちょっといいですか。", "Sumimasen, chotto ii desu ka.", "Excuse me, do you have a moment?"),
            ("Staff", "はい、どうしましたか。", "Hai, dou shimashita ka.", "Yes, how can I help?"),
            ("You", "新宿まで行きたいんですが、どうやって行けばいいですか。", "Shinjuku made ikitain desu ga, dou yatte ikeba ii desu ka.", "I want to go to Shinjuku. How should I get there?"),
            ("Staff", "電車とバスがありますが、電車のほうが早いですよ。", "Densha to basu ga arimasu ga, densha no hou ga hayai desu yo.", "There are trains and buses, but the train is faster."),
            ("You", "電車はどのくらいかかりますか。", "Densha wa dono kurai kakarimasu ka.", "How long does the train take?"),
            ("Staff", "特急で一時間半ぐらいです。", "Tokkyuu de ichijikan han gurai desu.", "About an hour and a half by limited express."),
            ("You", "いくらですか。", "Ikura desu ka.", "How much is it?"),
            ("Staff", "片道で三千二百五十円です。", "Katamichi de sanzen nihyaku gojuu en desu.", "It's 3,250 yen one way."),
            ("You", "じゃあ、特急の切符を一枚お願いします。", "Jaa, tokkyuu no kippu o ichimai onegai shimasu.", "Then one limited express ticket, please."),
            ("Staff", "次の電車は十時十五分発です。それでよろしいですか。", "Tsugi no densha wa juuji juugofun hatsu desu. Sore de yoroshii desu ka.", "The next train leaves at 10:15. Is that all right?"),
            ("You", "はい、大丈夫です。", "Hai, daijoubu desu.", "Yes, that's fine."),
            ("Staff", "窓側と通路側、どちらがいいですか。", "Madogawa to tsuurogawa, dochira ga ii desu ka.", "Window or aisle, which would you prefer?"),
            ("You", "窓側をお願いします。", "Madogawa o onegai shimasu.", "Window, please."),
            ("Staff", "かしこまりました。お支払いは現金ですか、カードですか。", "Kashikomarimashita. Oshiharai wa genkin desu ka, kaado desu ka.", "Certainly. Will you pay by cash or card?"),
            ("You", "カードでお願いします。", "Kaado de onegai shimasu.", "By card, please."),
            ("Staff", "こちらに差し込んで、暗証番号を入力してください。", "Kochira ni sashikonde, anshou bangou o nyuuryoku shite kudasai.", "Please insert it here and enter your PIN."),
            ("You", "はい、できました。", "Hai, dekimashita.", "Okay, done."),
            ("Staff", "こちらが切符です。四号車の十二番エー席です。", "Kochira ga kippu desu. Yongousha no juuniban ee seki desu.", "Here is your ticket. Car 4, seat 12A."),
            ("You", "ホームはどこですか。", "Hoomu wa doko desu ka.", "Where is the platform?"),
            ("Staff", "地下一階の一番線です。あちらのエスカレーターで降りてください。", "Chika ikkai no ichibansen desu. Achira no esukareetaa de orite kudasai.", "Track 1 on the first basement floor. Please go down that escalator."),
            ("You", "あと、スイカも買いたいんですが、どこで買えますか。", "Ato, Suika mo kaitain desu ga, doko de kaemasu ka.", "Also, I'd like to buy a Suica card. Where can I get one?"),
            ("Staff", "あちらの券売機で買えますよ。", "Achira no kenbaiki de kaemasu yo.", "You can buy one at that ticket machine."),
            ("You", "いくらですか。", "Ikura desu ka.", "How much is it?"),
            ("Staff", "二千円で、そのうち五百円はデポジットです。", "Nisen en de, sono uchi gohyaku en wa depojitto desu.", "It's 2,000 yen, and 500 yen of that is a deposit."),
            ("You", "英語の画面もありますか。", "Eigo no gamen mo arimasu ka.", "Is there an English screen too?"),
            ("Staff", "はい、右上のボタンで英語に変えられます。", "Hai, migiue no botan de eigo ni kaeraremasu.", "Yes, you can switch to English with the button on the upper right."),
            ("You", "分かりました。いろいろありがとうございます。", "Wakarimashita. Iroiro arigatou gozaimasu.", "Got it. Thanks for everything."),
            ("Staff", "いいえ。お気をつけて。", "Iie. Oki o tsukete.", "Not at all. Take care."),
        ],
    ),
    scenario(
        "hotel-check-in",
        "Hotel check-in",
        "Check in, ask about breakfast and Wi-Fi, and arrange to leave your bags after checkout.",
        setting="Hotel front desk",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Front desk", "いらっしゃいませ。チェックインでしょうか。", "Irasshaimase. Chekku in deshou ka.", "Welcome. Are you checking in?"),
            ("You", "はい、予約しているコナーです。", "Hai, yoyaku shite iru Konaa desu.", "Yes, I have a reservation. I'm Connor."),
            ("Front desk", "コナー様ですね。少々お待ちください。", "Konaa-sama desu ne. Shoushou omachi kudasai.", "Mr. Connor. One moment, please."),
            ("Front desk", "本日から三泊、ダブルルームでご予約いただいております。", "Honjitsu kara sanpaku, daburu ruumu de goyoyaku itadaite orimasu.", "You're booked for three nights from today in a double room."),
            ("You", "はい、そうです。", "Hai, sou desu.", "Yes, that's right."),
            ("Front desk", "パスポートをお預かりしてもよろしいですか。", "Pasupooto o oazukari shite mo yoroshii desu ka.", "May I take your passport for a moment?"),
            ("You", "はい、どうぞ。", "Hai, douzo.", "Yes, here you are."),
            ("Front desk", "ありがとうございます。コピーを取らせていただきます。", "Arigatou gozaimasu. Kopii o torasete itadakimasu.", "Thank you. I'll make a copy."),
            ("Front desk", "こちらの用紙に、お名前とご住所をお願いします。", "Kochira no youshi ni, onamae to gojuusho o onegai shimasu.", "Please write your name and address on this form."),
            ("You", "住所はアメリカの住所でいいですか。", "Juusho wa Amerika no juusho de ii desu ka.", "Is my American address okay?"),
            ("Front desk", "はい、大丈夫です。", "Hai, daijoubu desu.", "Yes, that's fine."),
            ("You", "書きました。", "Kakimashita.", "I've filled it in."),
            ("Front desk", "ありがとうございます。お部屋は八階の805号室です。", "Arigatou gozaimasu. Oheya wa hachikai no happyaku go gou shitsu desu.", "Thank you. Your room is 805 on the eighth floor."),
            ("Front desk", "こちらがカードキーです。", "Kochira ga kaado kii desu.", "Here's your key card."),
            ("You", "朝ごはんは付いていますか。", "Asagohan wa tsuite imasu ka.", "Is breakfast included?"),
            ("Front desk", "はい、朝食付きのプランです。二階のレストランで、六時半から十時までです。", "Hai, choushoku tsuki no puran desu. Nikai no resutoran de, rokuji han kara juuji made desu.", "Yes, your plan includes breakfast. It's in the second-floor restaurant from 6:30 to 10:00."),
            ("You", "ワイファイはありますか。", "Waifai wa arimasu ka.", "Is there Wi-Fi?"),
            ("Front desk", "はい、パスワードはこちらのカードに書いてあります。", "Hai, pasuwaado wa kochira no kaado ni kaite arimasu.", "Yes, the password is written on this card."),
            ("You", "チェックアウトは何時ですか。", "Chekku auto wa nanji desu ka.", "What time is checkout?"),
            ("Front desk", "十一時です。", "Juuichiji desu.", "Eleven o'clock."),
            ("You", "チェックアウトのあと、荷物を預かってもらえますか。", "Chekku auto no ato, nimotsu o azukatte moraemasu ka.", "Could you keep my luggage after checkout?"),
            ("Front desk", "はい、フロントでお預かりします。", "Hai, furonto de oazukari shimasu.", "Yes, we'll keep it at the front desk."),
            ("You", "よかった。最終日は夜の飛行機なんです。", "Yokatta. Saishuubi wa yoru no hikouki nan desu.", "Great. On my last day I have a night flight."),
            ("Front desk", "かしこまりました。何かございましたら、フロントまでお電話ください。", "Kashikomarimashita. Nanika gozaimashitara, furonto made odenwa kudasai.", "Understood. If you need anything, please call the front desk."),
            ("You", "近くにコンビニはありますか。", "Chikaku ni konbini wa arimasu ka.", "Is there a convenience store nearby?"),
            ("Front desk", "ホテルを出て、左に一分ほど歩くとございます。", "Hoteru o dete, hidari ni ippun hodo aruku to gozaimasu.", "Leave the hotel and walk left for about a minute, and you'll find one."),
            ("You", "ありがとうございます。", "Arigatou gozaimasu.", "Thank you."),
            ("Front desk", "どうぞごゆっくりお過ごしください。", "Douzo goyukkuri osugoshi kudasai.", "Please enjoy your stay."),
        ],
    ),
    scenario(
        "taxi-ride",
        "Taking a taxi",
        "Give the driver an address, chat about your trip, and pay at the end.",
        setting="Taxi in Tokyo",
        category=CATEGORY,
        level="Elementary",
        lines=[
            ("Driver", "どちらまでですか。", "Dochira made desu ka.", "Where to?"),
            ("You", "この住所までお願いします。", "Kono juusho made onegai shimasu.", "To this address, please."),
            ("Driver", "拝見します。ああ、浅草の近くですね。", "Haiken shimasu. Aa, Asakusa no chikaku desu ne.", "Let me see. Ah, that's near Asakusa."),
            ("You", "はい。どのくらいかかりますか。", "Hai. Dono kurai kakarimasu ka.", "Yes. How long will it take?"),
            ("Driver", "今の時間だと、二十分ぐらいですね。", "Ima no jikan da to, nijuppun gurai desu ne.", "At this time of day, about twenty minutes."),
            ("You", "いくらぐらいになりますか。", "Ikura gurai ni narimasu ka.", "About how much will it cost?"),
            ("Driver", "三千円ぐらいだと思います。", "Sanzen en gurai da to omoimasu.", "I think around 3,000 yen."),
            ("You", "分かりました。お願いします。", "Wakarimashita. Onegai shimasu.", "Okay. Let's go."),
            ("Driver", "シートベルトをお願いします。", "Shiitoberuto o onegai shimasu.", "Please fasten your seatbelt."),
            ("You", "はい。", "Hai.", "Okay."),
            ("Driver", "観光ですか。", "Kankou desu ka.", "Are you sightseeing?"),
            ("You", "はい、昨日日本に着きました。", "Hai, kinou Nihon ni tsukimashita.", "Yes, I arrived in Japan yesterday."),
            ("Driver", "そうですか。日本語がお上手ですね。", "Sou desu ka. Nihongo ga ojouzu desu ne.", "I see. Your Japanese is very good."),
            ("You", "いえいえ、まだまだです。毎日勉強しています。", "Ie ie, madamada desu. Mainichi benkyou shite imasu.", "Oh no, I still have a long way to go. I study every day."),
            ("Driver", "浅草ではどこに行きますか。", "Asakusa de wa doko ni ikimasu ka.", "Where will you go in Asakusa?"),
            ("You", "浅草寺に行きたいです。おすすめはありますか。", "Sensouji ni ikitai desu. Osusume wa arimasu ka.", "I want to go to Senso-ji. Any recommendations?"),
            ("Driver", "仲見世通りで食べ歩きをするのが楽しいですよ。人形焼きがおいしいです。", "Nakamise doori de tabearuki o suru no ga tanoshii desu yo. Ningyouyaki ga oishii desu.", "Snacking your way down Nakamise Street is fun. The ningyoyaki are delicious."),
            ("You", "人形焼きって何ですか。", "Ningyouyaki tte nan desu ka.", "What is ningyoyaki?"),
            ("Driver", "あんこが入った、小さいカステラです。", "Anko ga haitta, chiisai kasutera desu.", "It's a small sponge cake filled with sweet bean paste."),
            ("You", "おいしそうですね。食べてみます。", "Oishisou desu ne. Tabete mimasu.", "That sounds delicious. I'll try it."),
            ("Driver", "夜はスカイツリーもきれいに見えますよ。", "Yoru wa Sukaitsurii mo kirei ni miemasu yo.", "At night you can see the Skytree beautifully too."),
            ("You", "いいですね。あ、すみません、あの信号の先で止めてください。", "Ii desu ne. A, sumimasen, ano shingou no saki de tomete kudasai.", "Nice. Oh, excuse me, please stop just past that traffic light."),
            ("Driver", "はい、こちらでよろしいですか。", "Hai, kochira de yoroshii desu ka.", "Okay, is here all right?"),
            ("You", "はい、ここで大丈夫です。カードで払えますか。", "Hai, koko de daijoubu desu. Kaado de haraemasu ka.", "Yes, here is fine. Can I pay by card?"),
            ("Driver", "はい、使えます。二千八百円です。", "Hai, tsukaemasu. Nisen happyaku en desu.", "Yes, you can. It's 2,800 yen."),
            ("You", "お願いします。", "Onegai shimasu.", "Here you go."),
            ("Driver", "レシートです。お忘れ物のないように。", "Reshiito desu. Owasuremono no nai you ni.", "Here's your receipt. Don't forget anything."),
            ("You", "ありがとうございました。", "Arigatou gozaimashita.", "Thank you very much."),
            ("Driver", "楽しんでくださいね。", "Tanoshinde kudasai ne.", "Enjoy yourself!"),
        ],
    ),
    scenario(
        "missed-shinkansen",
        "Missed the Shinkansen",
        "You missed your reserved bullet train. Work out your options with the station staff.",
        setting="Tokyo Station ticket office",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("You", "すみません、乗るはずだった新幹線に乗り遅れてしまいました。", "Sumimasen, noru hazu datta shinkansen ni noriokurete shimaimashita.", "Excuse me, I missed the Shinkansen I was supposed to take."),
            ("Staff", "切符を見せていただけますか。", "Kippu o misete itadakemasu ka.", "Could you show me your ticket?"),
            ("You", "はい、これです。", "Hai, kore desu.", "Yes, here it is."),
            ("Staff", "九時半発の、のぞみ二十一号ですね。指定席ですか。", "Kuji han hatsu no, Nozomi nijuuichi gou desu ne. Shiteiseki desu ka.", "The 9:30 Nozomi 21. Is it a reserved seat?"),
            ("You", "はい、指定席です。もう使えませんか。", "Hai, shiteiseki desu. Mou tsukaemasen ka.", "Yes, reserved. Can I not use it anymore?"),
            ("Staff", "当日でしたら、後の新幹線の自由席に乗ることができますよ。", "Toujitsu deshitara, ato no shinkansen no jiyuuseki ni noru koto ga dekimasu yo.", "On the same day, you can ride in the unreserved cars of a later Shinkansen."),
            ("You", "自由席は何号車ですか。", "Jiyuuseki wa nangousha desu ka.", "Which cars are unreserved?"),
            ("Staff", "のぞみの場合は、一号車から三号車までです。", "Nozomi no baai wa, ichigousha kara sangousha made desu.", "For the Nozomi, cars 1 to 3."),
            ("You", "座れますか。", "Suwaremasu ka.", "Will I be able to sit?"),
            ("Staff", "今日は土曜日なので、少し混んでいるかもしれません。", "Kyou wa doyoubi na node, sukoshi konde iru kamoshiremasen.", "It's Saturday, so it might be a little crowded."),
            ("You", "新しく指定席を取ることはできますか。", "Atarashiku shiteiseki o toru koto wa dekimasu ka.", "Can I get a new reserved seat?"),
            ("Staff", "その場合は、もう一度特急券を買っていただくことになります。", "Sono baai wa, mou ichido tokkyuuken o katte itadaku koto ni narimasu.", "In that case, you'd need to buy a limited express ticket again."),
            ("You", "いくらかかりますか。", "Ikura kakarimasu ka.", "How much would that cost?"),
            ("Staff", "五千円ちょっとですね。", "Gosen en chotto desu ne.", "A little over 5,000 yen."),
            ("You", "うーん、じゃあ自由席にします。次の新幹線は何時ですか。", "Uun, jaa jiyuuseki ni shimasu. Tsugi no shinkansen wa nanji desu ka.", "Hmm, then I'll go unreserved. When is the next Shinkansen?"),
            ("Staff", "九時四十二分発があります。十八番線です。", "Kuji yonjuunifun hatsu ga arimasu. Juuhachibansen desu.", "There's one at 9:42. Track 18."),
            ("You", "十八番線には、どう行けばいいですか。", "Juuhachibansen ni wa, dou ikeba ii desu ka.", "How do I get to track 18?"),
            ("Staff", "この改札を入って、右側の階段を上がってください。", "Kono kaisatsu o haitte, migigawa no kaidan o agatte kudasai.", "Go through this ticket gate and up the stairs on the right."),
            ("You", "京都までは、どのくらいかかりますか。", "Kyouto made wa, dono kurai kakarimasu ka.", "How long does it take to Kyoto?"),
            ("Staff", "二時間十五分ぐらいです。", "Nijikan juugofun gurai desu.", "About two hours and fifteen minutes."),
            ("You", "お弁当を買う時間はありますか。", "Obentou o kau jikan wa arimasu ka.", "Do I have time to buy a bento?"),
            ("Staff", "ホームにも売店がありますから、大丈夫ですよ。", "Hoomu ni mo baiten ga arimasu kara, daijoubu desu yo.", "There are kiosks on the platform too, so you'll be fine."),
            ("You", "よかった。ご親切にありがとうございました。", "Yokatta. Goshinsetsu ni arigatou gozaimashita.", "Great. Thank you for your kindness."),
            ("Staff", "いえいえ。よい旅を。", "Ie ie. Yoi tabi o.", "Not at all. Have a good trip."),
        ],
    ),
    scenario(
        "lost-wallet",
        "Lost wallet at the police box",
        "Report a lost wallet at a koban, describe it, and find out where to pick it up.",
        setting="Koban (police box)",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("You", "すみません、財布をなくしてしまったんですが。", "Sumimasen, saifu o nakushite shimattan desu ga.", "Excuse me, I've lost my wallet."),
            ("Officer", "それは大変ですね。どこでなくしたか分かりますか。", "Sore wa taihen desu ne. Doko de nakushita ka wakarimasu ka.", "That's terrible. Do you know where you lost it?"),
            ("You", "たぶん電車の中だと思います。", "Tabun densha no naka da to omoimasu.", "I think it was probably on the train."),
            ("Officer", "何線の電車ですか。", "Nani sen no densha desu ka.", "Which line was it?"),
            ("You", "山手線です。渋谷から上野まで乗りました。", "Yamanotesen desu. Shibuya kara Ueno made norimashita.", "The Yamanote Line. I rode from Shibuya to Ueno."),
            ("Officer", "何時ごろでしたか。", "Nanji goro deshita ka.", "About what time was it?"),
            ("You", "午後二時ごろです。", "Gogo niji goro desu.", "Around 2 p.m."),
            ("Officer", "どんな財布ですか。", "Donna saifu desu ka.", "What does the wallet look like?"),
            ("You", "黒い革の財布で、これぐらいの大きさです。", "Kuroi kawa no saifu de, kore gurai no ookisa desu.", "It's a black leather wallet, about this size."),
            ("Officer", "中には何が入っていましたか。", "Naka ni wa nani ga haitte imashita ka.", "What was inside?"),
            ("You", "現金が一万円ぐらいと、クレジットカードが二枚と、ホテルのカードキーです。", "Genkin ga ichiman en gurai to, kurejitto kaado ga nimai to, hoteru no kaado kii desu.", "About 10,000 yen in cash, two credit cards, and my hotel key card."),
            ("Officer", "パスポートは大丈夫ですか。", "Pasupooto wa daijoubu desu ka.", "Is your passport safe?"),
            ("You", "はい、パスポートはかばんの中にあります。", "Hai, pasupooto wa kaban no naka ni arimasu.", "Yes, my passport is in my bag."),
            ("Officer", "よかったです。では、この書類に記入してください。", "Yokatta desu. Dewa, kono shorui ni kinyuu shite kudasai.", "Good. Then please fill out this form."),
            ("You", "日本の電話番号がないんですが、どうしたらいいですか。", "Nihon no denwa bangou ga nain desu ga, dou shitara ii desu ka.", "I don't have a Japanese phone number. What should I do?"),
            ("Officer", "ホテルの電話番号でも大丈夫ですよ。", "Hoteru no denwa bangou demo daijoubu desu yo.", "The hotel's phone number is fine."),
            ("You", "分かりました。書きました。", "Wakarimashita. Kakimashita.", "Okay. I've written it."),
            ("Officer", "今、駅の忘れ物センターに電話して確認してみますね。", "Ima, eki no wasuremono sentaa ni denwa shite kakunin shite mimasu ne.", "I'll call the station's lost-and-found center now and check."),
            ("You", "ありがとうございます。", "Arigatou gozaimasu.", "Thank you."),
            ("Officer", "お待たせしました。黒い革の財布が、上野駅に届いているそうです。", "Omatase shimashita. Kuroi kawa no saifu ga, Ueno eki ni todoite iru sou desu.", "Sorry to keep you waiting. Apparently a black leather wallet has been turned in at Ueno Station."),
            ("You", "本当ですか。よかった。", "Hontou desu ka. Yokatta.", "Really? Thank goodness."),
            ("Officer", "上野駅の駅員室に行って、この番号を言ってください。", "Ueno eki no ekiinshitsu ni itte, kono bangou o itte kudasai.", "Go to the station office at Ueno and give them this number."),
            ("You", "身分証明書が必要ですか。", "Mibun shoumeisho ga hitsuyou desu ka.", "Do I need ID?"),
            ("Officer", "はい、パスポートを持って行ってください。", "Hai, pasupooto o motte itte kudasai.", "Yes, please take your passport."),
            ("You", "日本では財布が戻ってくるって、本当なんですね。", "Nihon de wa saifu ga modotte kuru tte, hontou nan desu ne.", "So it's true that lost wallets come back in Japan."),
            ("Officer", "多くの場合はそうですね。でも、これからは気をつけてくださいね。", "Ooku no baai wa sou desu ne. Demo, kore kara wa ki o tsukete kudasai ne.", "Usually, yes. But please be careful from now on."),
            ("You", "はい、気をつけます。本当に助かりました。", "Hai, ki o tsukemasu. Hontou ni tasukarimashita.", "I will. You've really helped me."),
            ("Officer", "どういたしまして。", "Dou itashimashite.", "You're welcome."),
        ],
    ),
    scenario(
        "ryokan-stay",
        "Staying at a ryokan",
        "Arrive at a traditional inn: slippers and tatami, dinner in your room, hot spring manners, and yukata.",
        setting="Ryokan in Hakone",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("Okami", "ようこそいらっしゃいました。遠いところ、お疲れさまでした。", "Youkoso irasshaimashita. Tooi tokoro, otsukaresama deshita.", "Welcome. You must be tired after coming all this way."),
            ("You", "こんにちは。今日からお世話になります。", "Konnichiwa. Kyou kara osewa ni narimasu.", "Hello. Thank you for having me starting today."),
            ("Okami", "どうぞ、こちらで靴をお脱ぎください。", "Douzo, kochira de kutsu o onugi kudasai.", "Please take off your shoes here."),
            ("You", "スリッパを履いてもいいですか。", "Surippa o haite mo ii desu ka.", "May I wear the slippers?"),
            ("Okami", "はい、どうぞ。ただ、畳の上ではスリッパを脱いでくださいね。", "Hai, douzo. Tada, tatami no ue de wa surippa o nuide kudasai ne.", "Yes, please. But take them off on the tatami."),
            ("You", "分かりました。", "Wakarimashita.", "Understood."),
            ("Okami", "こちらがお部屋です。お茶をお入れしますね。", "Kochira ga oheya desu. Ocha o oire shimasu ne.", "This is your room. I'll make you some tea."),
            ("You", "わあ、きれいな部屋ですね。庭も見えます。", "Waa, kirei na heya desu ne. Niwa mo miemasu.", "Wow, what a beautiful room. I can see the garden too."),
            ("Okami", "ありがとうございます。この庭は、秋の紅葉がとても有名なんですよ。", "Arigatou gozaimasu. Kono niwa wa, aki no kouyou ga totemo yuumei nan desu yo.", "Thank you. This garden is famous for its autumn leaves."),
            ("Okami", "夕食は六時半から、こちらのお部屋にお持ちします。", "Yuushoku wa rokuji han kara, kochira no oheya ni omochi shimasu.", "We'll bring dinner to your room from 6:30."),
            ("You", "部屋で食べるんですか。楽しみです。", "Heya de taberun desu ka. Tanoshimi desu.", "We eat in the room? I'm looking forward to it."),
            ("Okami", "何か苦手な食べ物や、アレルギーはございますか。", "Nanika nigate na tabemono ya, arerugii wa gozaimasu ka.", "Is there any food you don't like, or any allergies?"),
            ("You", "生の卵が少し苦手です。", "Nama no tamago ga sukoshi nigate desu.", "I'm not great with raw eggs."),
            ("Okami", "かしこまりました。板前に伝えておきます。", "Kashikomarimashita. Itamae ni tsutaete okimasu.", "Certainly. I'll let the chef know."),
            ("You", "温泉は何時まで入れますか。", "Onsen wa nanji made hairemasu ka.", "Until what time can I use the hot spring?"),
            ("Okami", "大浴場は夜十二時までと、朝は五時から九時までです。", "Daiyokujou wa yoru juuniji made to, asa wa goji kara kuji made desu.", "The large bath is open until midnight, and from five to nine in the morning."),
            ("You", "温泉に入るのは初めてなんですが、何か気をつけることはありますか。", "Onsen ni hairu no wa hajimete nan desu ga, nanika ki o tsukeru koto wa arimasu ka.", "It's my first time at a hot spring. Is there anything I should be careful about?"),
            ("Okami", "まず、湯船に入る前に、体を洗ってください。", "Mazu, yubune ni hairu mae ni, karada o aratte kudasai.", "First, please wash your body before getting into the bath."),
            ("Okami", "それから、タオルはお湯の中に入れないでくださいね。", "Sore kara, taoru wa oyu no naka ni irenaide kudasai ne.", "Also, please don't put your towel in the water."),
            ("You", "タオルは頭の上に置けばいいですか。", "Taoru wa atama no ue ni okeba ii desu ka.", "Should I put the towel on my head?"),
            ("Okami", "はい、そうする方が多いですね。", "Hai, sou suru kata ga ooi desu ne.", "Yes, many people do that."),
            ("You", "浴衣はどうやって着ますか。", "Yukata wa dou yatte kimasu ka.", "How do I put on the yukata?"),
            ("Okami", "左側を上にして、帯を結んでください。", "Hidarigawa o ue ni shite, obi o musunde kudasai.", "Put the left side over the right and tie the sash."),
            ("Okami", "右が上だと、亡くなった方の着方になってしまいます。", "Migi ga ue da to, nakunatta kata no kikata ni natte shimaimasu.", "Right over left is how the deceased are dressed."),
            ("You", "えっ、それは知りませんでした。気をつけます。", "E, sore wa shirimasen deshita. Ki o tsukemasu.", "Oh, I didn't know that. I'll be careful."),
            ("Okami", "お布団は、夕食のあとに敷きに参ります。", "Ofuton wa, yuushoku no ato ni shiki ni mairimasu.", "We'll come and lay out the futons after dinner."),
            ("You", "何から何まで、ありがとうございます。", "Nani kara nani made, arigatou gozaimasu.", "Thank you for everything."),
            ("Okami", "どうぞ、ごゆっくりおくつろぎください。", "Douzo, goyukkuri okutsurogi kudasai.", "Please relax and make yourself at home."),
        ],
    ),
]
