from app.services.listening_content.base import scenario

CATEGORY = "Work & health"

WORK_SCENARIOS = [
    scenario(
        "first-day-at-work",
        "First day at a Japanese office",
        "Formal self-introduction, office tour, business cards, and the unwritten rules of a new workplace.",
        setting="Office reception and floor",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("Suzuki", "おはようございます。コナーさんですね。人事部の鈴木です。", "Ohayou gozaimasu. Konaa-san desu ne. Jinjibu no Suzuki desu.", "Good morning. You must be Connor. I'm Suzuki from HR."),
            ("You", "おはようございます。本日からお世話になります、コナーと申します。", "Ohayou gozaimasu. Honjitsu kara osewa ni narimasu, Konaa to moushimasu.", "Good morning. I'm Connor, and I'll be joining you from today."),
            ("Suzuki", "お待ちしていました。まず、部署の皆さんに紹介しますね。", "Omachi shite imashita. Mazu, busho no minasan ni shoukai shimasu ne.", "We've been expecting you. First, let me introduce you to the team."),
            ("Suzuki", "皆さん、ちょっといいですか。今日から営業部に入ったコナーさんです。", "Minasan, chotto ii desu ka. Kyou kara eigyoubu ni haitta Konaa-san desu.", "Everyone, do you have a moment? This is Connor, who joins Sales starting today."),
            ("You", "はじめまして。アメリカから参りました、コナーと申します。", "Hajimemashite. Amerika kara mairimashita, Konaa to moushimasu.", "How do you do. I'm Connor, from America."),
            ("You", "日本の会社で働くのは初めてなので、ご迷惑をおかけすることもあるかと思いますが、", "Nihon no kaisha de hataraku no wa hajimete na node, gomeiwaku o okake suru koto mo aru ka to omoimasu ga,", "This is my first time working at a Japanese company, so I may cause some trouble, but"),
            ("You", "一生懸命頑張りますので、どうぞよろしくお願いいたします。", "Isshoukenmei ganbarimasu node, douzo yoroshiku onegai itashimasu.", "I'll do my very best, so I humbly ask for your support."),
            ("Suzuki", "コナーさんの席は、こちらです。山田課長の隣ですね。", "Konaa-san no seki wa, kochira desu. Yamada kachou no tonari desu ne.", "Your desk is over here, next to Section Chief Yamada."),
            ("You", "パソコンは、もう使えますか。", "Pasokon wa, mou tsukaemasu ka.", "Can I use the computer already?"),
            ("Suzuki", "はい。パスワードはこの封筒に入っています。最初にログインしたら、必ず変更してください。", "Hai. Pasuwaado wa kono fuutou ni haitte imasu. Saisho ni roguin shitara, kanarazu henkou shite kudasai.", "Yes. Your password is in this envelope. Be sure to change it when you first log in."),
            ("Suzuki", "それから、名刺ができていますので、お渡ししますね。", "Sore kara, meishi ga dekite imasu node, owatashi shimasu ne.", "Also, your business cards are ready, so here you go."),
            ("You", "ありがとうございます。名刺交換のマナーを、教えていただけますか。", "Arigatou gozaimasu. Meishi koukan no manaa o, oshiete itadakemasu ka.", "Thank you. Could you teach me business card etiquette?"),
            ("Suzuki", "いいですよ。名刺は両手で、相手が読める向きで渡します。", "Ii desu yo. Meishi wa ryoute de, aite ga yomeru muki de watashimasu.", "Sure. Hand it over with both hands, facing so the other person can read it."),
            ("Suzuki", "もらった名刺は、すぐにしまわないで、会議の間は机の上に置いておきます。", "Moratta meishi wa, sugu ni shimawanaide, kaigi no aida wa tsukue no ue ni oite okimasu.", "Don't put away a card you receive right away. Keep it on the table during the meeting."),
            ("You", "ポケットに入れてはいけないんですね。", "Poketto ni irete wa ikenain desu ne.", "So I shouldn't put it in my pocket."),
            ("Suzuki", "そうです。特にズボンの後ろのポケットは、絶対にだめですよ。", "Sou desu. Toku ni zubon no ushiro no poketto wa, zettai ni dame desu yo.", "Right. And especially never in your back pants pocket."),
            ("You", "気をつけます。始業時間は九時ですよね。", "Ki o tsukemasu. Shigyou jikan wa kuji desu yo ne.", "I'll be careful. Work starts at nine, right?"),
            ("Suzuki", "はい。でも、皆さん十分前には来ていますね。朝礼が九時からあります。", "Hai. Demo, minasan juppun mae ni wa kite imasu ne. Chourei ga kuji kara arimasu.", "Yes, but everyone arrives ten minutes early. There's a morning meeting at nine."),
            ("You", "お昼休みは何時からですか。", "Ohiruyasumi wa nanji kara desu ka.", "When is lunch break?"),
            ("Suzuki", "十二時から一時までです。社員食堂が三階にありますよ。", "Juuniji kara ichiji made desu. Shain shokudou ga sangai ni arimasu yo.", "Twelve to one. There's an employee cafeteria on the third floor."),
            ("Suzuki", "何か分からないことがあったら、遠慮しないで聞いてくださいね。", "Nanika wakaranai koto ga attara, enryo shinaide kiite kudasai ne.", "If there's anything you don't understand, don't hesitate to ask."),
            ("You", "ありがとうございます。一つ質問してもよろしいでしょうか。", "Arigatou gozaimasu. Hitotsu shitsumon shite mo yoroshii deshou ka.", "Thank you. May I ask one question?"),
            ("Suzuki", "どうぞ。", "Douzo.", "Go ahead."),
            ("You", "仕事が終わって帰る時は、何と言えばいいですか。", "Shigoto ga owatte kaeru toki wa, nan to ieba ii desu ka.", "What should I say when I leave after work?"),
            ("Suzuki", "「お先に失礼します」と言います。残っている人は「お疲れ様でした」と返しますよ。", "\"Osaki ni shitsurei shimasu\" to iimasu. Nokotte iru hito wa \"otsukaresama deshita\" to kaeshimasu yo.", "You say \"Osaki ni shitsurei shimasu.\" People still working reply \"Otsukaresama deshita.\""),
            ("You", "「お先に失礼します」ですね。覚えました。", "\"Osaki ni shitsurei shimasu\" desu ne. Oboemashita.", "\"Osaki ni shitsurei shimasu.\" Got it."),
            ("Suzuki", "完璧です。では、十時からオリエンテーションがあるので、会議室に来てください。", "Kanpeki desu. Dewa, juuji kara orienteeshon ga aru node, kaigishitsu ni kite kudasai.", "Perfect. There's an orientation at ten, so please come to the meeting room."),
            ("You", "かしこまりました。", "Kashikomarimashita.", "Certainly."),
        ],
    ),
    scenario(
        "job-interview",
        "Part-time job interview",
        "Interview for a café job: experience, Japanese level, shifts, visa hours, and polite closing questions.",
        setting="Café back office",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("Manager", "本日はお越しいただき、ありがとうございます。店長の佐藤です。", "Honjitsu wa okoshi itadaki, arigatou gozaimasu. Tenchou no Satou desu.", "Thank you for coming today. I'm Sato, the store manager."),
            ("You", "コナーと申します。本日はよろしくお願いいたします。", "Konaa to moushimasu. Honjitsu wa yoroshiku onegai itashimasu.", "I'm Connor. Thank you for having me today."),
            ("Manager", "どうぞ、おかけください。", "Douzo, okake kudasai.", "Please, have a seat."),
            ("You", "失礼いたします。", "Shitsurei itashimasu.", "Thank you."),
            ("Manager", "では、まず簡単に自己紹介をお願いできますか。", "Dewa, mazu kantan ni jiko shoukai o onegai dekimasu ka.", "First, could you briefly introduce yourself?"),
            ("You", "はい。アメリカ出身で、現在は新宿の日本語学校に通っています。", "Hai. Amerika shusshin de, genzai wa Shinjuku no Nihongo gakkou ni kayotte imasu.", "Yes. I'm from America and currently attend a Japanese language school in Shinjuku."),
            ("You", "日本に来て半年になります。", "Nihon ni kite hantoshi ni narimasu.", "I've been in Japan for six months."),
            ("Manager", "どうして当店で働きたいと思ったんですか。", "Doushite touten de hatarakitai to omottan desu ka.", "Why do you want to work at our café?"),
            ("You", "よくお客さんとして来ていて、スタッフの方の丁寧な接客に感動したからです。", "Yoku okyakusan to shite kite ite, sutaffu no kata no teinei na sekkyaku ni kandou shita kara desu.", "I come here often as a customer, and I was impressed by how politely the staff treat people."),
            ("You", "それに、お客さんと話しながら、日本語をもっと上達させたいと思っています。", "Sore ni, okyakusan to hanashinagara, Nihongo o motto joutatsu sasetai to omotte imasu.", "Also, I want to improve my Japanese by talking with customers."),
            ("Manager", "飲食店で働いた経験はありますか。", "Inshokuten de hataraita keiken wa arimasu ka.", "Do you have experience working in food service?"),
            ("You", "はい、アメリカで二年間、カフェでバリスタをしていました。", "Hai, Amerika de ninenkan, kafe de barisuta o shite imashita.", "Yes, I worked as a barista at a café in America for two years."),
            ("Manager", "それは心強いですね。ラテアートもできますか。", "Sore wa kokorozuyoi desu ne. Rate aato mo dekimasu ka.", "That's reassuring. Can you do latte art?"),
            ("You", "ハートとリーフなら、できます。", "Haato to riifu nara, dekimasu.", "I can do hearts and leaves."),
            ("Manager", "日本語の敬語は、どのくらい使えますか。", "Nihongo no keigo wa, dono kurai tsukaemasu ka.", "How comfortable are you with keigo, polite Japanese?"),
            ("You", "接客でよく使う表現は、学校で練習しました。まだ完璧ではありませんが、毎日勉強しています。", "Sekkyaku de yoku tsukau hyougen wa, gakkou de renshuu shimashita. Mada kanpeki de wa arimasen ga, mainichi benkyou shite imasu.", "I practiced common customer-service phrases at school. It's not perfect yet, but I study every day."),
            ("Manager", "週に何日ぐらい入れますか。", "Shuu ni nannichi gurai hairemasu ka.", "How many days a week can you work?"),
            ("You", "学校が午前中なので、平日の午後と、土日は一日中大丈夫です。", "Gakkou ga gozenchuu na node, heijitsu no gogo to, donichi wa ichinichijuu daijoubu desu.", "School is in the mornings, so weekday afternoons and all day on weekends are fine."),
            ("You", "ただ、留学生のビザなので、週二十八時間までしか働けません。", "Tada, ryuugakusei no biza na node, shuu nijuuhachi jikan made shika hatarakemasen.", "However, I'm on a student visa, so I can only work up to 28 hours a week."),
            ("Manager", "大丈夫ですよ。資格外活動許可は、お持ちですか。", "Daijoubu desu yo. Shikakugai katsudou kyoka wa, omochi desu ka.", "That's fine. Do you have a permit to work outside your visa status?"),
            ("You", "はい、在留カードの裏に記載されています。", "Hai, zairyuu kaado no ura ni kisai sarete imasu.", "Yes, it's noted on the back of my residence card."),
            ("Manager", "確認させてください。", "Kakunin sasete kudasai.", "Please let me check it."),
            ("Manager", "はい、問題ありません。最後に、何か質問はありますか。", "Hai, mondai arimasen. Saigo ni, nanika shitsumon wa arimasu ka.", "Yes, no problem. Lastly, do you have any questions?"),
            ("You", "研修期間はありますか。", "Kenshuu kikan wa arimasu ka.", "Is there a training period?"),
            ("Manager", "最初の二週間は研修で、先輩と一緒にシフトに入ってもらいます。", "Saisho no nishuukan wa kenshuu de, senpai to issho ni shifuto ni haitte moraimasu.", "The first two weeks are training, and you'll work shifts alongside a senior staff member."),
            ("You", "安心しました。結果は、いつごろ分かりますか。", "Anshin shimashita. Kekka wa, itsu goro wakarimasu ka.", "That's reassuring. When will I hear the result?"),
            ("Manager", "三日以内に、お電話でご連絡します。", "Mikka inai ni, odenwa de gorenraku shimasu.", "We'll call you within three days."),
            ("You", "承知いたしました。本日はお忙しいところ、ありがとうございました。", "Shouchi itashimashita. Honjitsu wa oisogashii tokoro, arigatou gozaimashita.", "Understood. Thank you for your time today despite your busy schedule."),
            ("Manager", "こちらこそ、ありがとうございました。", "Kochira koso, arigatou gozaimashita.", "Thank you as well."),
        ],
    ),
    scenario(
        "doctor-visit",
        "Seeing a doctor",
        "Check in at a clinic, describe symptoms in detail, get a diagnosis, and understand the prescription.",
        setting="Neighborhood clinic",
        category=CATEGORY,
        level="Intermediate",
        lines=[
            ("Reception", "こんにちは。今日はどうされましたか。", "Konnichiwa. Kyou wa dou saremashita ka.", "Hello. What brings you in today?"),
            ("You", "昨日の夜から、お腹が痛くて、熱もあります。", "Kinou no yoru kara, onaka ga itakute, netsu mo arimasu.", "Since last night I've had a stomachache and a fever."),
            ("Reception", "こちらは初めてですか。", "Kochira wa hajimete desu ka.", "Is this your first visit here?"),
            ("You", "はい、初めてです。", "Hai, hajimete desu.", "Yes, it's my first time."),
            ("Reception", "では、保険証を見せていただけますか。それから、この問診票にご記入ください。", "Dewa, hokenshou o misete itadakemasu ka. Sore kara, kono monshinhyou ni gokinyuu kudasai.", "Then may I see your insurance card? And please fill out this medical questionnaire."),
            ("You", "すみません、漢字が少し難しいので、手伝っていただけますか。", "Sumimasen, kanji ga sukoshi muzukashii node, tetsudatte itadakemasu ka.", "Sorry, the kanji is a bit hard for me. Could you help?"),
            ("Reception", "もちろんです。アレルギーはありますか。", "Mochiron desu. Arerugii wa arimasu ka.", "Of course. Do you have any allergies?"),
            ("You", "ペニシリンのアレルギーがあります。", "Penishirin no arerugii ga arimasu.", "I'm allergic to penicillin."),
            ("Reception", "大事なことですね。書いておきます。お名前が呼ばれるまで、お待ちください。", "Daiji na koto desu ne. Kaite okimasu. Onamae ga yobareru made, omachi kudasai.", "That's important. I'll note it. Please wait until your name is called."),
            ("Doctor", "コナーさん、どうぞ。今日はどうしましたか。", "Konaa-san, douzo. Kyou wa dou shimashita ka.", "Connor, come in. What seems to be the problem?"),
            ("You", "昨日の夜から、お腹が痛いんです。", "Kinou no yoru kara, onaka ga itain desu.", "My stomach has hurt since last night."),
            ("Doctor", "どのあたりが痛みますか。", "Dono atari ga itamimasu ka.", "Where does it hurt?"),
            ("You", "このへんです。おへその下のあたりです。", "Kono hen desu. Oheso no shita no atari desu.", "Around here. Below my belly button."),
            ("Doctor", "どんな痛みですか。ずきずきしますか、それとも、きりきりしますか。", "Donna itami desu ka. Zukizuki shimasu ka, soretomo, kirikiri shimasu ka.", "What kind of pain? Throbbing, or sharp and stabbing?"),
            ("You", "きりきりする感じです。時々、強くなります。", "Kirikiri suru kanji desu. Tokidoki, tsuyoku narimasu.", "Sharp, stabbing. Sometimes it gets stronger."),
            ("Doctor", "熱は何度ありましたか。", "Netsu wa nando arimashita ka.", "How high was your fever?"),
            ("You", "今朝測ったら、三十八度ありました。", "Kesa hakattara, sanjuuhachi do arimashita.", "When I checked this morning, it was 38 degrees."),
            ("Doctor", "吐き気や下痢はありますか。", "Hakike ya geri wa arimasu ka.", "Any nausea or diarrhea?"),
            ("You", "少し吐き気があります。下痢も、何回かありました。", "Sukoshi hakike ga arimasu. Geri mo, nankai ka arimashita.", "A little nausea. And diarrhea a few times."),
            ("Doctor", "昨日、何か変わったものを食べましたか。", "Kinou, nanika kawatta mono o tabemashita ka.", "Did you eat anything unusual yesterday?"),
            ("You", "お昼に、屋台で生の牡蠣を食べました。", "Ohiru ni, yatai de nama no kaki o tabemashita.", "For lunch I ate raw oysters at a food stall."),
            ("Doctor", "なるほど。ちょっとお腹を見せてください。ここを押すと痛いですか。", "Naruhodo. Chotto onaka o misete kudasai. Koko o osu to itai desu ka.", "I see. Let me examine your stomach. Does it hurt when I press here?"),
            ("You", "いたた、はい、痛いです。", "Itata, hai, itai desu.", "Ow, yes, that hurts."),
            ("Doctor", "おそらく、胃腸炎ですね。牡蠣が原因かもしれません。", "Osoraku, ichouen desu ne. Kaki ga gen'in ka mo shiremasen.", "It's most likely gastroenteritis. The oysters may be the cause."),
            ("You", "重い病気ですか。", "Omoi byouki desu ka.", "Is it serious?"),
            ("Doctor", "心配いりません。三日ぐらいで良くなると思います。", "Shinpai irimasen. Mikka gurai de yoku naru to omoimasu.", "Don't worry. You should get better in about three days."),
            ("Doctor", "整腸剤と、熱を下げる薬を出しておきます。ペニシリンの入っていない薬ですから、安心してください。", "Seichouzai to, netsu o sageru kusuri o dashite okimasu. Penishirin no haitte inai kusuri desu kara, anshin shite kudasai.", "I'll prescribe something to settle your stomach and a fever reducer. Neither contains penicillin, so don't worry."),
            ("You", "薬はどうやって飲めばいいですか。", "Kusuri wa dou yatte nomeba ii desu ka.", "How should I take the medicine?"),
            ("Doctor", "一日三回、食後に飲んでください。熱の薬は、三十八度以上の時だけで大丈夫です。", "Ichinichi sankai, shokugo ni nonde kudasai. Netsu no kusuri wa, sanjuuhachi do ijou no toki dake de daijoubu desu.", "Three times a day after meals. Take the fever medicine only when it's 38 degrees or higher."),
            ("Doctor", "水分をたくさんとって、今日と明日は、消化にいいものを食べてくださいね。", "Suibun o takusan totte, kyou to ashita wa, shouka ni ii mono o tabete kudasai ne.", "Drink plenty of fluids, and eat easy-to-digest food today and tomorrow."),
            ("You", "例えば、どんなものがいいですか。", "Tatoeba, donna mono ga ii desu ka.", "For example, what's good?"),
            ("Doctor", "おかゆや、うどんがいいですね。脂っこいものとお酒は、やめてください。", "Okayu ya, udon ga ii desu ne. Aburakkoi mono to osake wa, yamete kudasai.", "Rice porridge or udon are good. Please avoid greasy food and alcohol."),
            ("You", "分かりました。仕事は休んだほうがいいですか。", "Wakarimashita. Shigoto wa yasunda hou ga ii desu ka.", "Understood. Should I take time off work?"),
            ("Doctor", "うつる可能性があるので、熱が下がるまでは休んでください。", "Utsuru kanousei ga aru node, netsu ga sagaru made wa yasunde kudasai.", "It may be contagious, so please rest until the fever goes down."),
            ("Doctor", "三日たっても良くならなかったら、また来てください。", "Mikka tatte mo yoku naranakattara, mata kite kudasai.", "If you're not better after three days, come back."),
            ("You", "ありがとうございました。お大事にと言いたいところですが、それは先生のセリフですね。", "Arigatou gozaimashita. Odaiji ni to iitai tokoro desu ga, sore wa sensei no serifu desu ne.", "Thank you. I'd say \"take care,\" but that's your line, doctor."),
            ("Doctor", "あはは、その通りです。お大事に。", "Ahaha, sono toori desu. Odaiji ni.", "Ha ha, that's right. Take care."),
        ],
    ),
]
