from typing import Optional

from pydantic import BaseModel


class FlashcardSeed(BaseModel):
    id: str
    english: str
    kana: str
    romaji: str
    kind: str = "vocabulary"
    example_kana: Optional[str] = None
    example_romaji: Optional[str] = None
    example_english: Optional[str] = None


BASIC_FLASHCARDS = [
    FlashcardSeed(
        id="hello",
        english="hello",
        kana="こんにちは",
        romaji="konnichiwa",
        example_kana="こんにちは、田中さん。",
        example_romaji="Konnichiwa, Tanaka-san.",
        example_english="Hello, Mr. Tanaka.",
    ),
    FlashcardSeed(
        id="good-morning",
        english="good morning",
        kana="おはようございます",
        romaji="ohayou gozaimasu",
        kind="phrase",
    ),
    FlashcardSeed(
        id="good-evening",
        english="good evening",
        kana="こんばんは",
        romaji="konbanwa",
        kind="phrase",
    ),
    FlashcardSeed(
        id="thank-you",
        english="thank you",
        kana="ありがとうございます",
        romaji="arigatou gozaimasu",
        kind="phrase",
    ),
    FlashcardSeed(
        id="excuse-me",
        english="excuse me",
        kana="すみません",
        romaji="sumimasen",
        kind="phrase",
    ),
    FlashcardSeed(
        id="yes",
        english="yes",
        kana="はい",
        romaji="hai",
        example_kana="はい、そうです。",
        example_romaji="Hai, sou desu.",
        example_english="Yes, that's right.",
    ),
    FlashcardSeed(
        id="no",
        english="no",
        kana="いいえ",
        romaji="iie",
        example_kana="いいえ、ちがいます。",
        example_romaji="Iie, chigaimasu.",
        example_english="No, that's different.",
    ),
    FlashcardSeed(
        id="please",
        english="please",
        kana="おねがいします",
        romaji="onegaishimasu",
        kind="phrase",
    ),
    FlashcardSeed(
        id="water",
        english="water",
        kana="みず",
        romaji="mizu",
        example_kana="みずをください。",
        example_romaji="Mizu o kudasai.",
        example_english="Please give me water.",
    ),
    FlashcardSeed(
        id="tea",
        english="tea",
        kana="おちゃ",
        romaji="ocha",
        example_kana="おちゃをのみます。",
        example_romaji="Ocha o nomimasu.",
        example_english="I drink tea.",
    ),
    FlashcardSeed(
        id="rice-meal",
        english="rice / meal",
        kana="ごはん",
        romaji="gohan",
        example_kana="あさごはんをたべます。",
        example_romaji="Asagohan o tabemasu.",
        example_english="I eat breakfast.",
    ),
    FlashcardSeed(
        id="friend",
        english="friend",
        kana="ともだち",
        romaji="tomodachi",
        example_kana="ともだちとべんきょうします。",
        example_romaji="Tomodachi to benkyou shimasu.",
        example_english="I study with a friend.",
    ),
    FlashcardSeed(
        id="teacher",
        english="teacher",
        kana="せんせい",
        romaji="sensei",
        example_kana="せんせいにききます。",
        example_romaji="Sensei ni kikimasu.",
        example_english="I ask the teacher.",
    ),
    FlashcardSeed(
        id="student",
        english="student",
        kana="がくせい",
        romaji="gakusei",
        example_kana="わたしはがくせいです。",
        example_romaji="Watashi wa gakusei desu.",
        example_english="I am a student.",
    ),
    FlashcardSeed(
        id="school",
        english="school",
        kana="がっこう",
        romaji="gakkou",
        example_kana="がっこうにいきます。",
        example_romaji="Gakkou ni ikimasu.",
        example_english="I go to school.",
    ),
    FlashcardSeed(
        id="home",
        english="home",
        kana="いえ",
        romaji="ie",
        example_kana="いえにかえります。",
        example_romaji="Ie ni kaerimasu.",
        example_english="I return home.",
    ),
    FlashcardSeed(
        id="station",
        english="station",
        kana="えき",
        romaji="eki",
        example_kana="えきはどこですか。",
        example_romaji="Eki wa doko desu ka.",
        example_english="Where is the station?",
    ),
    FlashcardSeed(
        id="store",
        english="store",
        kana="みせ",
        romaji="mise",
        example_kana="みせでかいます。",
        example_romaji="Mise de kaimasu.",
        example_english="I buy it at the store.",
    ),
    FlashcardSeed(
        id="person",
        english="person",
        kana="ひと",
        romaji="hito",
        example_kana="あのひとはやさしいです。",
        example_romaji="Ano hito wa yasashii desu.",
        example_english="That person is kind.",
    ),
    FlashcardSeed(
        id="today",
        english="today",
        kana="きょう",
        romaji="kyou",
        example_kana="きょうはあついです。",
        example_romaji="Kyou wa atsui desu.",
        example_english="Today is hot.",
    ),
    FlashcardSeed(
        id="tomorrow",
        english="tomorrow",
        kana="あした",
        romaji="ashita",
        example_kana="あしたいきます。",
        example_romaji="Ashita ikimasu.",
        example_english="I will go tomorrow.",
    ),
    FlashcardSeed(
        id="yesterday",
        english="yesterday",
        kana="きのう",
        romaji="kinou",
        example_kana="きのうべんきょうしました。",
        example_romaji="Kinou benkyou shimashita.",
        example_english="I studied yesterday.",
    ),
    FlashcardSeed(
        id="now",
        english="now",
        kana="いま",
        romaji="ima",
        example_kana="いまなんじですか。",
        example_romaji="Ima nanji desu ka.",
        example_english="What time is it now?",
    ),
    FlashcardSeed(
        id="go",
        english="to go",
        kana="いく",
        romaji="iku",
        example_kana="にほんにいきます。",
        example_romaji="Nihon ni ikimasu.",
        example_english="I go to Japan.",
    ),
    FlashcardSeed(
        id="come",
        english="to come",
        kana="くる",
        romaji="kuru",
        example_kana="ともだちがきます。",
        example_romaji="Tomodachi ga kimasu.",
        example_english="My friend comes.",
    ),
    FlashcardSeed(
        id="eat",
        english="to eat",
        kana="たべる",
        romaji="taberu",
        example_kana="すしをたべます。",
        example_romaji="Sushi o tabemasu.",
        example_english="I eat sushi.",
    ),
    FlashcardSeed(
        id="drink",
        english="to drink",
        kana="のむ",
        romaji="nomu",
        example_kana="みずをのみます。",
        example_romaji="Mizu o nomimasu.",
        example_english="I drink water.",
    ),
    FlashcardSeed(
        id="see",
        english="to see / watch",
        kana="みる",
        romaji="miru",
        example_kana="えいがをみます。",
        example_romaji="Eiga o mimasu.",
        example_english="I watch a movie.",
    ),
    FlashcardSeed(
        id="listen-ask",
        english="to listen / ask",
        kana="きく",
        romaji="kiku",
        example_kana="おんがくをききます。",
        example_romaji="Ongaku o kikimasu.",
        example_english="I listen to music.",
    ),
    FlashcardSeed(
        id="speak",
        english="to speak",
        kana="はなす",
        romaji="hanasu",
        example_kana="にほんごをはなします。",
        example_romaji="Nihongo o hanashimasu.",
        example_english="I speak Japanese.",
    ),
    FlashcardSeed(
        id="read",
        english="to read",
        kana="よむ",
        romaji="yomu",
        example_kana="ほんをよみます。",
        example_romaji="Hon o yomimasu.",
        example_english="I read a book.",
    ),
    FlashcardSeed(
        id="write",
        english="to write",
        kana="かく",
        romaji="kaku",
        example_kana="なまえをかきます。",
        example_romaji="Namae o kakimasu.",
        example_english="I write my name.",
    ),
    FlashcardSeed(
        id="understand",
        english="to understand",
        kana="わかる",
        romaji="wakaru",
        example_kana="にほんごがわかります。",
        example_romaji="Nihongo ga wakarimasu.",
        example_english="I understand Japanese.",
    ),
    FlashcardSeed(
        id="like",
        english="like",
        kana="すき",
        romaji="suki",
        example_kana="ねこがすきです。",
        example_romaji="Neko ga suki desu.",
        example_english="I like cats.",
    ),
    FlashcardSeed(
        id="big",
        english="big",
        kana="おおきい",
        romaji="ookii",
        example_kana="おおきいかばんです。",
        example_romaji="Ookii kaban desu.",
        example_english="It is a big bag.",
    ),
    FlashcardSeed(
        id="small",
        english="small",
        kana="ちいさい",
        romaji="chiisai",
        example_kana="ちいさいいぬです。",
        example_romaji="Chiisai inu desu.",
        example_english="It is a small dog.",
    ),
    FlashcardSeed(
        id="delicious",
        english="delicious",
        kana="おいしい",
        romaji="oishii",
        example_kana="ラーメンはおいしいです。",
        example_romaji="Raamen wa oishii desu.",
        example_english="Ramen is delicious.",
    ),
    FlashcardSeed(
        id="where",
        english="where?",
        kana="どこですか",
        romaji="doko desu ka",
        kind="phrase",
    ),
    FlashcardSeed(
        id="how-much",
        english="how much is it?",
        kana="いくらですか",
        romaji="ikura desu ka",
        kind="phrase",
    ),
    FlashcardSeed(
        id="i-dont-understand",
        english="I don't understand",
        kana="わかりません",
        romaji="wakarimasen",
        kind="phrase",
    ),
    FlashcardSeed(
        id="one-more-time",
        english="one more time, please",
        kana="もういちどおねがいします",
        romaji="mou ichido onegaishimasu",
        kind="phrase",
    ),
    FlashcardSeed(
        id="morning",
        english="morning",
        kana="あさ",
        romaji="asa",
        example_kana="あさにコーヒーをのみます。",
        example_romaji="Asa ni koohii o nomimasu.",
        example_english="I drink coffee in the morning.",
    ),
    FlashcardSeed(
        id="night",
        english="night",
        kana="よる",
        romaji="yoru",
        example_kana="よるにほんをよみます。",
        example_romaji="Yoru ni hon o yomimasu.",
        example_english="I read a book at night.",
    ),
    FlashcardSeed(
        id="cat",
        english="cat",
        kana="ねこ",
        romaji="neko",
        example_kana="ねこがねています。",
        example_romaji="Neko ga nete imasu.",
        example_english="The cat is sleeping.",
    ),
    FlashcardSeed(
        id="dog",
        english="dog",
        kana="いぬ",
        romaji="inu",
        example_kana="いぬとさんぽします。",
        example_romaji="Inu to sanpo shimasu.",
        example_english="I take a walk with the dog.",
    ),
    FlashcardSeed(
        id="book",
        english="book",
        kana="ほん",
        romaji="hon",
        example_kana="ほんをかいます。",
        example_romaji="Hon o kaimasu.",
        example_english="I buy a book.",
    ),
    FlashcardSeed(
        id="car",
        english="car",
        kana="くるま",
        romaji="kuruma",
        example_kana="くるまでいきます。",
        example_romaji="Kuruma de ikimasu.",
        example_english="I go by car.",
    ),
    FlashcardSeed(
        id="train",
        english="train",
        kana="でんしゃ",
        romaji="densha",
        example_kana="でんしゃにのります。",
        example_romaji="Densha ni norimasu.",
        example_english="I ride the train.",
    ),
    FlashcardSeed(
        id="bicycle",
        english="bicycle",
        kana="じてんしゃ",
        romaji="jitensha",
        example_kana="じてんしゃでがっこうにいきます。",
        example_romaji="Jitensha de gakkou ni ikimasu.",
        example_english="I go to school by bicycle.",
    ),
    FlashcardSeed(
        id="bus",
        english="bus",
        kana="バス",
        romaji="basu",
        example_kana="バスをまちます。",
        example_romaji="Basu o machimasu.",
        example_english="I wait for the bus.",
    ),
    FlashcardSeed(
        id="taxi",
        english="taxi",
        kana="タクシー",
        romaji="takushii",
        example_kana="タクシーをつかいます。",
        example_romaji="Takushii o tsukaimasu.",
        example_english="I use a taxi.",
    ),
    FlashcardSeed(
        id="airplane",
        english="airplane",
        kana="ひこうき",
        romaji="hikouki",
        example_kana="ひこうきでにほんにいきます。",
        example_romaji="Hikouki de Nihon ni ikimasu.",
        example_english="I go to Japan by airplane.",
    ),
    FlashcardSeed(
        id="phone",
        english="phone",
        kana="でんわ",
        romaji="denwa",
        example_kana="でんわをします。",
        example_romaji="Denwa o shimasu.",
        example_english="I make a phone call.",
    ),
    FlashcardSeed(
        id="bag",
        english="bag",
        kana="かばん",
        romaji="kaban",
        example_kana="かばんはおおきいです。",
        example_romaji="Kaban wa ookii desu.",
        example_english="The bag is big.",
    ),
    FlashcardSeed(
        id="umbrella",
        english="umbrella",
        kana="かさ",
        romaji="kasa",
        example_kana="かさをもっています。",
        example_romaji="Kasa o motte imasu.",
        example_english="I have an umbrella.",
    ),
    FlashcardSeed(
        id="shoes",
        english="shoes",
        kana="くつ",
        romaji="kutsu",
        example_kana="くつをかいます。",
        example_romaji="Kutsu o kaimasu.",
        example_english="I buy shoes.",
    ),
    FlashcardSeed(
        id="clothes",
        english="clothes",
        kana="ふく",
        romaji="fuku",
        example_kana="あたらしいふくをきます。",
        example_romaji="Atarashii fuku o kimasu.",
        example_english="I wear new clothes.",
    ),
    FlashcardSeed(
        id="money",
        english="money",
        kana="おかね",
        romaji="okane",
        example_kana="おかねがあります。",
        example_romaji="Okane ga arimasu.",
        example_english="I have money.",
    ),
    FlashcardSeed(
        id="time",
        english="time",
        kana="じかん",
        romaji="jikan",
        example_kana="じかんがありません。",
        example_romaji="Jikan ga arimasen.",
        example_english="I don't have time.",
    ),
    FlashcardSeed(
        id="name",
        english="name",
        kana="なまえ",
        romaji="namae",
        example_kana="なまえをかきます。",
        example_romaji="Namae o kakimasu.",
        example_english="I write my name.",
    ),
    FlashcardSeed(
        id="country",
        english="country",
        kana="くに",
        romaji="kuni",
        example_kana="どこのくにですか。",
        example_romaji="Doko no kuni desu ka.",
        example_english="Which country is it?",
    ),
    FlashcardSeed(
        id="japan",
        english="Japan",
        kana="にほん",
        romaji="nihon",
        example_kana="にほんにいきたいです。",
        example_romaji="Nihon ni ikitai desu.",
        example_english="I want to go to Japan.",
    ),
    FlashcardSeed(
        id="japanese-language",
        english="Japanese language",
        kana="にほんご",
        romaji="nihongo",
        example_kana="にほんごをべんきょうします。",
        example_romaji="Nihongo o benkyou shimasu.",
        example_english="I study Japanese.",
    ),
    FlashcardSeed(
        id="english-language",
        english="English language",
        kana="えいご",
        romaji="eigo",
        example_kana="えいごがわかります。",
        example_romaji="Eigo ga wakarimasu.",
        example_english="I understand English.",
    ),
    FlashcardSeed(
        id="mother",
        english="mother",
        kana="おかあさん",
        romaji="okaasan",
        example_kana="おかあさんにでんわします。",
        example_romaji="Okaasan ni denwa shimasu.",
        example_english="I call my mother.",
    ),
    FlashcardSeed(
        id="father",
        english="father",
        kana="おとうさん",
        romaji="otousan",
        example_kana="おとうさんはやさしいです。",
        example_romaji="Otousan wa yasashii desu.",
        example_english="My father is kind.",
    ),
    FlashcardSeed(
        id="older-brother",
        english="older brother",
        kana="おにいさん",
        romaji="oniisan",
        example_kana="おにいさんはがくせいです。",
        example_romaji="Oniisan wa gakusei desu.",
        example_english="My older brother is a student.",
    ),
    FlashcardSeed(
        id="older-sister",
        english="older sister",
        kana="おねえさん",
        romaji="oneesan",
        example_kana="おねえさんとみせにいきます。",
        example_romaji="Oneesan to mise ni ikimasu.",
        example_english="I go to the store with my older sister.",
    ),
    FlashcardSeed(
        id="child",
        english="child",
        kana="こども",
        romaji="kodomo",
        example_kana="こどもがあそんでいます。",
        example_romaji="Kodomo ga asonde imasu.",
        example_english="The child is playing.",
    ),
    FlashcardSeed(
        id="man",
        english="man",
        kana="おとこのひと",
        romaji="otoko no hito",
        example_kana="あのおとこのひとはせんせいです。",
        example_romaji="Ano otoko no hito wa sensei desu.",
        example_english="That man is a teacher.",
    ),
    FlashcardSeed(
        id="woman",
        english="woman",
        kana="おんなのひと",
        romaji="onna no hito",
        example_kana="あのおんなのひとはともだちです。",
        example_romaji="Ano onna no hito wa tomodachi desu.",
        example_english="That woman is my friend.",
    ),
    FlashcardSeed(
        id="left",
        english="left",
        kana="ひだり",
        romaji="hidari",
        example_kana="ひだりにまがります。",
        example_romaji="Hidari ni magarimasu.",
        example_english="I turn left.",
    ),
    FlashcardSeed(
        id="right",
        english="right",
        kana="みぎ",
        romaji="migi",
        example_kana="みぎにあります。",
        example_romaji="Migi ni arimasu.",
        example_english="It is on the right.",
    ),
    FlashcardSeed(
        id="front",
        english="front",
        kana="まえ",
        romaji="mae",
        example_kana="えきのまえにいます。",
        example_romaji="Eki no mae ni imasu.",
        example_english="I am in front of the station.",
    ),
    FlashcardSeed(
        id="back",
        english="back / behind",
        kana="うしろ",
        romaji="ushiro",
        example_kana="いえのうしろにあります。",
        example_romaji="Ie no ushiro ni arimasu.",
        example_english="It is behind the house.",
    ),
    FlashcardSeed(
        id="up",
        english="up / above",
        kana="うえ",
        romaji="ue",
        example_kana="つくえのうえにあります。",
        example_romaji="Tsukue no ue ni arimasu.",
        example_english="It is on top of the desk.",
    ),
    FlashcardSeed(
        id="down",
        english="down / below",
        kana="した",
        romaji="shita",
        example_kana="いすのしたにあります。",
        example_romaji="Isu no shita ni arimasu.",
        example_english="It is under the chair.",
    ),
    FlashcardSeed(
        id="inside",
        english="inside",
        kana="なか",
        romaji="naka",
        example_kana="かばんのなかにあります。",
        example_romaji="Kaban no naka ni arimasu.",
        example_english="It is inside the bag.",
    ),
    FlashcardSeed(
        id="outside",
        english="outside",
        kana="そと",
        romaji="soto",
        example_kana="そとでまちます。",
        example_romaji="Soto de machimasu.",
        example_english="I wait outside.",
    ),
    FlashcardSeed(
        id="hot-weather",
        english="hot",
        kana="あつい",
        romaji="atsui",
        example_kana="きょうはあついです。",
        example_romaji="Kyou wa atsui desu.",
        example_english="Today is hot.",
    ),
    FlashcardSeed(
        id="cold-weather",
        english="cold",
        kana="さむい",
        romaji="samui",
        example_kana="よるはさむいです。",
        example_romaji="Yoru wa samui desu.",
        example_english="The night is cold.",
    ),
    FlashcardSeed(
        id="fun",
        english="fun",
        kana="たのしい",
        romaji="tanoshii",
        example_kana="べんきょうはたのしいです。",
        example_romaji="Benkyou wa tanoshii desu.",
        example_english="Studying is fun.",
    ),
    FlashcardSeed(
        id="difficult",
        english="difficult",
        kana="むずかしい",
        romaji="muzukashii",
        example_kana="にほんごはむずかしいです。",
        example_romaji="Nihongo wa muzukashii desu.",
        example_english="Japanese is difficult.",
    ),
    FlashcardSeed(
        id="easy",
        english="easy",
        kana="かんたん",
        romaji="kantan",
        example_kana="これはかんたんです。",
        example_romaji="Kore wa kantan desu.",
        example_english="This is easy.",
    ),
    FlashcardSeed(
        id="new",
        english="new",
        kana="あたらしい",
        romaji="atarashii",
        example_kana="あたらしいほんです。",
        example_romaji="Atarashii hon desu.",
        example_english="It is a new book.",
    ),
    FlashcardSeed(
        id="old",
        english="old",
        kana="ふるい",
        romaji="furui",
        example_kana="ふるいいえです。",
        example_romaji="Furui ie desu.",
        example_english="It is an old house.",
    ),
    FlashcardSeed(
        id="fast",
        english="fast",
        kana="はやい",
        romaji="hayai",
        example_kana="でんしゃははやいです。",
        example_romaji="Densha wa hayai desu.",
        example_english="The train is fast.",
    ),
    FlashcardSeed(
        id="slow",
        english="slow",
        kana="おそい",
        romaji="osoi",
        example_kana="バスはおそいです。",
        example_romaji="Basu wa osoi desu.",
        example_english="The bus is slow.",
    ),
    FlashcardSeed(
        id="near",
        english="near",
        kana="ちかい",
        romaji="chikai",
        example_kana="えきはちかいです。",
        example_romaji="Eki wa chikai desu.",
        example_english="The station is near.",
    ),
    FlashcardSeed(
        id="far",
        english="far",
        kana="とおい",
        romaji="tooi",
        example_kana="がっこうはとおいです。",
        example_romaji="Gakkou wa tooi desu.",
        example_english="The school is far.",
    ),
    FlashcardSeed(
        id="buy",
        english="to buy",
        kana="かう",
        romaji="kau",
        example_kana="パンをかいます。",
        example_romaji="Pan o kaimasu.",
        example_english="I buy bread.",
    ),
    FlashcardSeed(
        id="wait",
        english="to wait",
        kana="まつ",
        romaji="matsu",
        example_kana="ここでまちます。",
        example_romaji="Koko de machimasu.",
        example_english="I wait here.",
    ),
    FlashcardSeed(
        id="use",
        english="to use",
        kana="つかう",
        romaji="tsukau",
        example_kana="でんわをつかいます。",
        example_romaji="Denwa o tsukaimasu.",
        example_english="I use the phone.",
    ),
    FlashcardSeed(
        id="make",
        english="to make",
        kana="つくる",
        romaji="tsukuru",
        example_kana="ばんごはんをつくります。",
        example_romaji="Bangohan o tsukurimasu.",
        example_english="I make dinner.",
    ),
    FlashcardSeed(
        id="sleep",
        english="to sleep",
        kana="ねる",
        romaji="neru",
        example_kana="よるにねます。",
        example_romaji="Yoru ni nemasu.",
        example_english="I sleep at night.",
    ),
    FlashcardSeed(
        id="wake-up",
        english="to wake up",
        kana="おきる",
        romaji="okiru",
        example_kana="あさにおきます。",
        example_romaji="Asa ni okimasu.",
        example_english="I wake up in the morning.",
    ),
    FlashcardSeed(
        id="work",
        english="to work",
        kana="はたらく",
        romaji="hataraku",
        example_kana="みせではたらきます。",
        example_romaji="Mise de hatarakimasu.",
        example_english="I work at a store.",
    ),
    FlashcardSeed(
        id="study",
        english="to study",
        kana="べんきょうする",
        romaji="benkyou suru",
        example_kana="まいにちべんきょうします。",
        example_romaji="Mainichi benkyou shimasu.",
        example_english="I study every day.",
    ),
    FlashcardSeed(
        id="meet",
        english="to meet",
        kana="あう",
        romaji="au",
        example_kana="ともだちにあいます。",
        example_romaji="Tomodachi ni aimasu.",
        example_english="I meet a friend.",
    ),
    FlashcardSeed(
        id="enter",
        english="to enter",
        kana="はいる",
        romaji="hairu",
        example_kana="へやにはいります。",
        example_romaji="Heya ni hairimasu.",
        example_english="I enter the room.",
    ),
]
