from pydantic import BaseModel


class PassiveListeningItemSeed(BaseModel):
    id: str
    english: str
    japanese: str
    romaji: str


class PassiveListeningCategorySeed(BaseModel):
    id: str
    title: str
    description: str
    items: list[PassiveListeningItemSeed]


PASSIVE_LISTENING_CATEGORIES = [
    PassiveListeningCategorySeed(
        id="food",
        title="Food",
        description="Basic food and restaurant words for everyday listening.",
        items=[
            PassiveListeningItemSeed(id="water", english="water", japanese="みず", romaji="mizu"),
            PassiveListeningItemSeed(id="tea", english="tea", japanese="おちゃ", romaji="ocha"),
            PassiveListeningItemSeed(id="rice-meal", english="rice or meal", japanese="ごはん", romaji="gohan"),
            PassiveListeningItemSeed(id="bread", english="bread", japanese="パン", romaji="pan"),
            PassiveListeningItemSeed(id="fish", english="fish", japanese="さかな", romaji="sakana"),
            PassiveListeningItemSeed(id="meat", english="meat", japanese="にく", romaji="niku"),
            PassiveListeningItemSeed(id="vegetables", english="vegetables", japanese="やさい", romaji="yasai"),
            PassiveListeningItemSeed(id="fruit", english="fruit", japanese="くだもの", romaji="kudamono"),
            PassiveListeningItemSeed(id="delicious", english="delicious", japanese="おいしい", romaji="oishii"),
            PassiveListeningItemSeed(id="water-please", english="water, please", japanese="みずをください", romaji="mizu o kudasai"),
            PassiveListeningItemSeed(id="coffee", english="coffee", japanese="コーヒー", romaji="koohii"),
            PassiveListeningItemSeed(id="milk", english="milk", japanese="ぎゅうにゅう", romaji="gyuunyuu"),
            PassiveListeningItemSeed(id="egg", english="egg", japanese="たまご", romaji="tamago"),
            PassiveListeningItemSeed(id="chicken", english="chicken", japanese="とりにく", romaji="toriniku"),
            PassiveListeningItemSeed(id="soup", english="soup", japanese="スープ", romaji="suupu"),
            PassiveListeningItemSeed(id="spicy", english="spicy", japanese="からい", romaji="karai"),
            PassiveListeningItemSeed(id="sweet", english="sweet", japanese="あまい", romaji="amai"),
            PassiveListeningItemSeed(id="menu", english="menu", japanese="メニュー", romaji="menyuu"),
            PassiveListeningItemSeed(id="bill", english="bill or check", japanese="おかいけい", romaji="okaikei"),
            PassiveListeningItemSeed(id="i-am-full", english="I am full", japanese="おなかがいっぱいです", romaji="onaka ga ippai desu"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="greetings",
        title="Greetings",
        description="Polite greetings and social basics.",
        items=[
            PassiveListeningItemSeed(id="hello", english="hello", japanese="こんにちは", romaji="konnichiwa"),
            PassiveListeningItemSeed(id="good-morning", english="good morning", japanese="おはようございます", romaji="ohayou gozaimasu"),
            PassiveListeningItemSeed(id="good-evening", english="good evening", japanese="こんばんは", romaji="konbanwa"),
            PassiveListeningItemSeed(id="goodbye", english="goodbye", japanese="さようなら", romaji="sayounara"),
            PassiveListeningItemSeed(id="thank-you", english="thank you", japanese="ありがとうございます", romaji="arigatou gozaimasu"),
            PassiveListeningItemSeed(id="excuse-me", english="excuse me", japanese="すみません", romaji="sumimasen"),
            PassiveListeningItemSeed(id="nice-to-meet-you", english="nice to meet you", japanese="はじめまして", romaji="hajimemashite"),
            PassiveListeningItemSeed(id="please", english="please", japanese="おねがいします", romaji="onegaishimasu"),
            PassiveListeningItemSeed(id="yes", english="yes", japanese="はい", romaji="hai"),
            PassiveListeningItemSeed(id="no", english="no", japanese="いいえ", romaji="iie"),
            PassiveListeningItemSeed(id="see-you", english="see you later", japanese="またあとで", romaji="mata ato de"),
            PassiveListeningItemSeed(id="good-night", english="good night", japanese="おやすみなさい", romaji="oyasuminasai"),
            PassiveListeningItemSeed(id="sorry", english="I'm sorry", japanese="ごめんなさい", romaji="gomennasai"),
            PassiveListeningItemSeed(id="no-problem", english="no problem", japanese="だいじょうぶです", romaji="daijoubu desu"),
            PassiveListeningItemSeed(id="my-name-is", english="my name is Connor", japanese="わたしのなまえはコナーです", romaji="watashi no namae wa Konaa desu"),
            PassiveListeningItemSeed(id="what-is-your-name", english="what is your name?", japanese="おなまえはなんですか", romaji="onamae wa nan desu ka"),
            PassiveListeningItemSeed(id="nice-weather", english="nice weather", japanese="いいてんきですね", romaji="ii tenki desu ne"),
            PassiveListeningItemSeed(id="take-care", english="take care", japanese="きをつけて", romaji="ki o tsukete"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="travel",
        title="Travel",
        description="Words and phrases for getting around.",
        items=[
            PassiveListeningItemSeed(id="station", english="station", japanese="えき", romaji="eki"),
            PassiveListeningItemSeed(id="train", english="train", japanese="でんしゃ", romaji="densha"),
            PassiveListeningItemSeed(id="bus", english="bus", japanese="バス", romaji="basu"),
            PassiveListeningItemSeed(id="taxi", english="taxi", japanese="タクシー", romaji="takushii"),
            PassiveListeningItemSeed(id="airport", english="airport", japanese="くうこう", romaji="kuukou"),
            PassiveListeningItemSeed(id="hotel", english="hotel", japanese="ホテル", romaji="hoteru"),
            PassiveListeningItemSeed(id="left", english="left", japanese="ひだり", romaji="hidari"),
            PassiveListeningItemSeed(id="right", english="right", japanese="みぎ", romaji="migi"),
            PassiveListeningItemSeed(id="where-is-station", english="where is the station?", japanese="えきはどこですか", romaji="eki wa doko desu ka"),
            PassiveListeningItemSeed(id="go-to-japan", english="I go to Japan", japanese="にほんにいきます", romaji="nihon ni ikimasu"),
            PassiveListeningItemSeed(id="ticket", english="ticket", japanese="きっぷ", romaji="kippu"),
            PassiveListeningItemSeed(id="platform", english="platform", japanese="ホーム", romaji="hoomu"),
            PassiveListeningItemSeed(id="map", english="map", japanese="ちず", romaji="chizu"),
            PassiveListeningItemSeed(id="here", english="here", japanese="ここ", romaji="koko"),
            PassiveListeningItemSeed(id="there", english="there", japanese="そこ", romaji="soko"),
            PassiveListeningItemSeed(id="over-there", english="over there", japanese="あそこ", romaji="asoko"),
            PassiveListeningItemSeed(id="nearby", english="nearby", japanese="ちかく", romaji="chikaku"),
            PassiveListeningItemSeed(id="please-stop-here", english="please stop here", japanese="ここでとめてください", romaji="koko de tomete kudasai"),
            PassiveListeningItemSeed(id="which-platform", english="which platform?", japanese="どのホームですか", romaji="dono hoomu desu ka"),
            PassiveListeningItemSeed(id="is-this-train-ok", english="is this train okay?", japanese="このでんしゃでいいですか", romaji="kono densha de ii desu ka"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="daily-life",
        title="Daily Life",
        description="Common words for home, work, and routine.",
        items=[
            PassiveListeningItemSeed(id="today", english="today", japanese="きょう", romaji="kyou"),
            PassiveListeningItemSeed(id="tomorrow", english="tomorrow", japanese="あした", romaji="ashita"),
            PassiveListeningItemSeed(id="yesterday", english="yesterday", japanese="きのう", romaji="kinou"),
            PassiveListeningItemSeed(id="morning", english="morning", japanese="あさ", romaji="asa"),
            PassiveListeningItemSeed(id="night", english="night", japanese="よる", romaji="yoru"),
            PassiveListeningItemSeed(id="home", english="home", japanese="いえ", romaji="ie"),
            PassiveListeningItemSeed(id="school", english="school", japanese="がっこう", romaji="gakkou"),
            PassiveListeningItemSeed(id="work", english="to work", japanese="はたらく", romaji="hataraku"),
            PassiveListeningItemSeed(id="study", english="to study", japanese="べんきょうする", romaji="benkyou suru"),
            PassiveListeningItemSeed(id="sleep", english="to sleep", japanese="ねる", romaji="neru"),
            PassiveListeningItemSeed(id="wake-up", english="to wake up", japanese="おきる", romaji="okiru"),
            PassiveListeningItemSeed(id="eat-breakfast", english="to eat breakfast", japanese="あさごはんをたべる", romaji="asagohan o taberu"),
            PassiveListeningItemSeed(id="go-home", english="to go home", japanese="いえにかえる", romaji="ie ni kaeru"),
            PassiveListeningItemSeed(id="clean", english="to clean", japanese="そうじする", romaji="souji suru"),
            PassiveListeningItemSeed(id="wash", english="to wash", japanese="あらう", romaji="arau"),
            PassiveListeningItemSeed(id="shower", english="shower", japanese="シャワー", romaji="shawaa"),
            PassiveListeningItemSeed(id="family", english="family", japanese="かぞく", romaji="kazoku"),
            PassiveListeningItemSeed(id="room", english="room", japanese="へや", romaji="heya"),
            PassiveListeningItemSeed(id="desk", english="desk", japanese="つくえ", romaji="tsukue"),
            PassiveListeningItemSeed(id="chair", english="chair", japanese="いす", romaji="isu"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="survival-phrases",
        title="Survival Phrases",
        description="Short phrases for real conversations.",
        items=[
            PassiveListeningItemSeed(id="i-dont-understand", english="I don't understand", japanese="わかりません", romaji="wakarimasen"),
            PassiveListeningItemSeed(id="one-more-time", english="one more time, please", japanese="もういちどおねがいします", romaji="mou ichido onegaishimasu"),
            PassiveListeningItemSeed(id="slowly-please", english="slowly, please", japanese="ゆっくりおねがいします", romaji="yukkuri onegaishimasu"),
            PassiveListeningItemSeed(id="where", english="where is it?", japanese="どこですか", romaji="doko desu ka"),
            PassiveListeningItemSeed(id="how-much", english="how much is it?", japanese="いくらですか", romaji="ikura desu ka"),
            PassiveListeningItemSeed(id="this-please", english="this, please", japanese="これをください", romaji="kore o kudasai"),
            PassiveListeningItemSeed(id="i-am-okay", english="I am okay", japanese="だいじょうぶです", romaji="daijoubu desu"),
            PassiveListeningItemSeed(id="help-me", english="please help me", japanese="たすけてください", romaji="tasukete kudasai"),
            PassiveListeningItemSeed(id="bathroom", english="where is the bathroom?", japanese="トイレはどこですか", romaji="toire wa doko desu ka"),
            PassiveListeningItemSeed(id="i-speak-little", english="I speak a little Japanese", japanese="にほんごをすこしはなします", romaji="nihongo o sukoshi hanashimasu"),
            PassiveListeningItemSeed(id="do-you-speak-english", english="do you speak English?", japanese="えいごをはなしますか", romaji="eigo o hanashimasu ka"),
            PassiveListeningItemSeed(id="please-write-it", english="please write it", japanese="かいてください", romaji="kaite kudasai"),
            PassiveListeningItemSeed(id="please-say-it", english="please say it", japanese="いってください", romaji="itte kudasai"),
            PassiveListeningItemSeed(id="i-am-lost", english="I am lost", japanese="まよいました", romaji="mayoimashita"),
            PassiveListeningItemSeed(id="i-need-a-doctor", english="I need a doctor", japanese="いしゃがひつようです", romaji="isha ga hitsuyou desu"),
            PassiveListeningItemSeed(id="call-police", english="please call the police", japanese="けいさつをよんでください", romaji="keisatsu o yonde kudasai"),
            PassiveListeningItemSeed(id="can-i-use-card", english="can I use a card?", japanese="カードはつかえますか", romaji="kaado wa tsukaemasu ka"),
            PassiveListeningItemSeed(id="cash-only", english="cash only?", japanese="げんきんだけですか", romaji="genkin dake desu ka"),
            PassiveListeningItemSeed(id="one-moment", english="one moment, please", japanese="ちょっとまってください", romaji="chotto matte kudasai"),
            PassiveListeningItemSeed(id="no-thank-you", english="no thank you", japanese="いいえ、けっこうです", romaji="iie, kekkou desu"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="numbers-time",
        title="Numbers and Time",
        description="Numbers, time words, and useful counting phrases.",
        items=[
            PassiveListeningItemSeed(id="one", english="one", japanese="いち", romaji="ichi"),
            PassiveListeningItemSeed(id="two", english="two", japanese="に", romaji="ni"),
            PassiveListeningItemSeed(id="three", english="three", japanese="さん", romaji="san"),
            PassiveListeningItemSeed(id="four", english="four", japanese="よん", romaji="yon"),
            PassiveListeningItemSeed(id="five", english="five", japanese="ご", romaji="go"),
            PassiveListeningItemSeed(id="six", english="six", japanese="ろく", romaji="roku"),
            PassiveListeningItemSeed(id="seven", english="seven", japanese="なな", romaji="nana"),
            PassiveListeningItemSeed(id="eight", english="eight", japanese="はち", romaji="hachi"),
            PassiveListeningItemSeed(id="nine", english="nine", japanese="きゅう", romaji="kyuu"),
            PassiveListeningItemSeed(id="ten", english="ten", japanese="じゅう", romaji="juu"),
            PassiveListeningItemSeed(id="what-time", english="what time is it?", japanese="なんじですか", romaji="nanji desu ka"),
            PassiveListeningItemSeed(id="one-oclock", english="one o'clock", japanese="いちじ", romaji="ichiji"),
            PassiveListeningItemSeed(id="half-past", english="half past", japanese="はん", romaji="han"),
            PassiveListeningItemSeed(id="today-time", english="today at three", japanese="きょうのさんじ", romaji="kyou no sanji"),
            PassiveListeningItemSeed(id="how-many", english="how many?", japanese="いくつですか", romaji="ikutsu desu ka"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="people-family",
        title="People and Family",
        description="People, family members, and relationship words.",
        items=[
            PassiveListeningItemSeed(id="person", english="person", japanese="ひと", romaji="hito"),
            PassiveListeningItemSeed(id="friend", english="friend", japanese="ともだち", romaji="tomodachi"),
            PassiveListeningItemSeed(id="teacher", english="teacher", japanese="せんせい", romaji="sensei"),
            PassiveListeningItemSeed(id="student", english="student", japanese="がくせい", romaji="gakusei"),
            PassiveListeningItemSeed(id="mother", english="mother", japanese="おかあさん", romaji="okaasan"),
            PassiveListeningItemSeed(id="father", english="father", japanese="おとうさん", romaji="otousan"),
            PassiveListeningItemSeed(id="older-brother", english="older brother", japanese="おにいさん", romaji="oniisan"),
            PassiveListeningItemSeed(id="older-sister", english="older sister", japanese="おねえさん", romaji="oneesan"),
            PassiveListeningItemSeed(id="child", english="child", japanese="こども", romaji="kodomo"),
            PassiveListeningItemSeed(id="everyone", english="everyone", japanese="みなさん", romaji="minasan"),
            PassiveListeningItemSeed(id="man", english="man", japanese="おとこのひと", romaji="otoko no hito"),
            PassiveListeningItemSeed(id="woman", english="woman", japanese="おんなのひと", romaji="onna no hito"),
            PassiveListeningItemSeed(id="my-friend", english="my friend", japanese="わたしのともだち", romaji="watashi no tomodachi"),
            PassiveListeningItemSeed(id="my-family", english="my family", japanese="わたしのかぞく", romaji="watashi no kazoku"),
            PassiveListeningItemSeed(id="who-is-that", english="who is that?", japanese="あのひとはだれですか", romaji="ano hito wa dare desu ka"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="verbs-actions",
        title="Verbs and Actions",
        description="Common actions you hear in everyday speech.",
        items=[
            PassiveListeningItemSeed(id="go", english="to go", japanese="いく", romaji="iku"),
            PassiveListeningItemSeed(id="come", english="to come", japanese="くる", romaji="kuru"),
            PassiveListeningItemSeed(id="eat", english="to eat", japanese="たべる", romaji="taberu"),
            PassiveListeningItemSeed(id="drink", english="to drink", japanese="のむ", romaji="nomu"),
            PassiveListeningItemSeed(id="see", english="to see", japanese="みる", romaji="miru"),
            PassiveListeningItemSeed(id="listen", english="to listen", japanese="きく", romaji="kiku"),
            PassiveListeningItemSeed(id="speak", english="to speak", japanese="はなす", romaji="hanasu"),
            PassiveListeningItemSeed(id="read", english="to read", japanese="よむ", romaji="yomu"),
            PassiveListeningItemSeed(id="write", english="to write", japanese="かく", romaji="kaku"),
            PassiveListeningItemSeed(id="buy", english="to buy", japanese="かう", romaji="kau"),
            PassiveListeningItemSeed(id="wait", english="to wait", japanese="まつ", romaji="matsu"),
            PassiveListeningItemSeed(id="use", english="to use", japanese="つかう", romaji="tsukau"),
            PassiveListeningItemSeed(id="make", english="to make", japanese="つくる", romaji="tsukuru"),
            PassiveListeningItemSeed(id="meet", english="to meet", japanese="あう", romaji="au"),
            PassiveListeningItemSeed(id="enter", english="to enter", japanese="はいる", romaji="hairu"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="places",
        title="Places",
        description="Locations you will hear while navigating Japan.",
        items=[
            PassiveListeningItemSeed(id="store", english="store", japanese="みせ", romaji="mise"),
            PassiveListeningItemSeed(id="restaurant", english="restaurant", japanese="レストラン", romaji="resutoran"),
            PassiveListeningItemSeed(id="cafe", english="cafe", japanese="カフェ", romaji="kafe"),
            PassiveListeningItemSeed(id="convenience-store", english="convenience store", japanese="コンビニ", romaji="konbini"),
            PassiveListeningItemSeed(id="hospital", english="hospital", japanese="びょういん", romaji="byouin"),
            PassiveListeningItemSeed(id="bank", english="bank", japanese="ぎんこう", romaji="ginkou"),
            PassiveListeningItemSeed(id="post-office", english="post office", japanese="ゆうびんきょく", romaji="yuubinkyoku"),
            PassiveListeningItemSeed(id="park", english="park", japanese="こうえん", romaji="kouen"),
            PassiveListeningItemSeed(id="library", english="library", japanese="としょかん", romaji="toshokan"),
            PassiveListeningItemSeed(id="bathroom-place", english="bathroom", japanese="トイレ", romaji="toire"),
            PassiveListeningItemSeed(id="room-place", english="room", japanese="へや", romaji="heya"),
            PassiveListeningItemSeed(id="front-place", english="front", japanese="まえ", romaji="mae"),
            PassiveListeningItemSeed(id="behind-place", english="behind", japanese="うしろ", romaji="ushiro"),
            PassiveListeningItemSeed(id="inside-place", english="inside", japanese="なか", romaji="naka"),
            PassiveListeningItemSeed(id="outside-place", english="outside", japanese="そと", romaji="soto"),
        ],
    ),
    PassiveListeningCategorySeed(
        id="adjectives",
        title="Descriptions",
        description="Simple adjectives for describing things.",
        items=[
            PassiveListeningItemSeed(id="big", english="big", japanese="おおきい", romaji="ookii"),
            PassiveListeningItemSeed(id="small", english="small", japanese="ちいさい", romaji="chiisai"),
            PassiveListeningItemSeed(id="new", english="new", japanese="あたらしい", romaji="atarashii"),
            PassiveListeningItemSeed(id="old", english="old", japanese="ふるい", romaji="furui"),
            PassiveListeningItemSeed(id="hot", english="hot", japanese="あつい", romaji="atsui"),
            PassiveListeningItemSeed(id="cold", english="cold", japanese="さむい", romaji="samui"),
            PassiveListeningItemSeed(id="fun", english="fun", japanese="たのしい", romaji="tanoshii"),
            PassiveListeningItemSeed(id="difficult", english="difficult", japanese="むずかしい", romaji="muzukashii"),
            PassiveListeningItemSeed(id="easy", english="easy", japanese="かんたん", romaji="kantan"),
            PassiveListeningItemSeed(id="fast", english="fast", japanese="はやい", romaji="hayai"),
            PassiveListeningItemSeed(id="slow", english="slow", japanese="おそい", romaji="osoi"),
            PassiveListeningItemSeed(id="near", english="near", japanese="ちかい", romaji="chikai"),
            PassiveListeningItemSeed(id="far", english="far", japanese="とおい", romaji="tooi"),
            PassiveListeningItemSeed(id="quiet", english="quiet", japanese="しずか", romaji="shizuka"),
            PassiveListeningItemSeed(id="busy", english="busy", japanese="いそがしい", romaji="isogashii"),
        ],
    ),
]
