import { useCallback, useEffect, useRef, useState } from "react";
import { getSpanishAudio, type SpanishAudioRequestItem } from "@/lib/api";
import { detachAudio, playAudioElement, replaceAudio } from "@/lib/audioPlayback";
import { speakableSpanish } from "@/lib/spanishText";
import type { AudioAsset } from "@/types/study";

export type SpanishVoice = "primary" | "secondary";

const BATCH_SIZE = 200;
const POLL_INTERVAL_MS = 1500;
const readyAssets = new Map<string, AudioAsset>();

function cacheKey(item: Pick<SpanishAudioRequestItem, "text" | "language" | "voice">) {
  return `${item.language}:${item.voice ?? "primary"}:${item.text.trim()}`;
}

function isReady(asset: AudioAsset | undefined): boolean {
  return Boolean(asset && asset.status === "ready" && asset.public_url);
}

function isTransientLookupFailure(asset: AudioAsset) {
  return asset.status === "failed" && Boolean(asset.error_message?.startsWith("Could not load cached audio"));
}

function wait(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}

/**
 * Resolves native Mexican Spanish (and English prompt) audio for each item. New clips are
 * generated by ElevenLabs in the background, so pending assets are polled for up to
 * `maxPolls` rounds before returning whatever state they are in.
 */
export async function loadSpanishAudio(
  items: SpanishAudioRequestItem[],
  { maxPolls = 4 }: { maxPolls?: number } = {},
): Promise<Record<string, AudioAsset>> {
  const results: Record<string, AudioAsset> = {};
  let outstanding: SpanishAudioRequestItem[] = [];

  for (const item of items) {
    const cached = readyAssets.get(cacheKey(item));
    if (cached) results[item.id] = cached;
    else outstanding.push(item);
  }

  for (let attempt = 0; outstanding.length && attempt <= maxPolls; attempt += 1) {
    if (attempt > 0) await wait(POLL_INTERVAL_MS);
    const batches = Array.from(
      { length: Math.ceil(outstanding.length / BATCH_SIZE) },
      (_, index) => outstanding.slice(index * BATCH_SIZE, (index + 1) * BATCH_SIZE),
    );
    const manifest = (await Promise.all(batches.map((batch) => getSpanishAudio(batch)))).flat();
    const byId = new Map(manifest.map((entry) => [entry.id, entry.audio]));

    outstanding = outstanding.filter((item) => {
      const asset = byId.get(item.id);
      if (!asset) return false;
      results[item.id] = asset;
      if (isReady(asset)) {
        readyAssets.set(cacheKey(item), asset);
        return false;
      }
      return asset.status === "pending" || isTransientLookupFailure(asset);
    });
  }

  return results;
}

export function prefetchSpanishAudio(texts: string[], voice: SpanishVoice = "primary") {
  const unique = Array.from(new Set(texts.map(speakableSpanish).filter(Boolean)));
  if (!unique.length) return;
  void loadSpanishAudio(
    unique.map((text, index) => ({ id: `prefetch:${index}`, text, language: "es", voice })),
    { maxPolls: 0 },
  ).catch(() => undefined);
}

function speakWithBrowser(text: string, rate: number) {
  if (typeof window === "undefined" || !("speechSynthesis" in window)) return false;
  window.speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(text);
  const voices = window.speechSynthesis.getVoices();
  const voice =
    voices.find((item) => item.lang.toLowerCase() === "es-mx") ??
    voices.find((item) => item.lang.toLowerCase().startsWith("es-4") || item.lang.toLowerCase() === "es-us") ??
    voices.find((item) => item.lang.toLowerCase().startsWith("es"));
  utterance.lang = voice?.lang ?? "es-MX";
  if (voice) utterance.voice = voice;
  utterance.rate = rate * 0.9;
  window.speechSynthesis.speak(utterance);
  return true;
}

/**
 * Click-to-play helper for Spanish text using the native es-MX ElevenLabs voices.
 * `slow` plays the same clip at a reduced rate (pitch is preserved by the browser).
 */
export function useSpanishSpeech() {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const requestRef = useRef(0);
  const [loadingText, setLoadingText] = useState<string | null>(null);
  const [playingText, setPlayingText] = useState<string | null>(null);

  useEffect(
    () => () => {
      detachAudio(audioRef.current);
      audioRef.current = null;
    },
    [],
  );

  const stop = useCallback(() => {
    requestRef.current += 1;
    detachAudio(audioRef.current);
    audioRef.current = null;
    setLoadingText(null);
    setPlayingText(null);
  }, []);

  const speak = useCallback(
    async (
      text: string,
      { voice = "primary", slow = false }: { voice?: SpanishVoice; slow?: boolean } = {},
    ) => {
      const trimmed = text.trim();
      if (!trimmed) return;
      const requestId = requestRef.current + 1;
      requestRef.current = requestId;
      detachAudio(audioRef.current);
      audioRef.current = null;
      setPlayingText(null);
      setLoadingText(trimmed);
      const rate = slow ? 0.72 : 1;

      try {
        const assets = await loadSpanishAudio(
          [{ id: "speak", text: speakableSpanish(trimmed), language: "es", voice }],
          { maxPolls: 10 },
        );
        if (requestRef.current !== requestId) return;
        const asset = assets.speak;
        if (!isReady(asset)) throw new Error(asset?.error_message ?? "Audio is not ready yet.");

        const audio = replaceAudio(audioRef.current, asset.public_url as string, { playbackRate: rate });
        audioRef.current = audio;
        setLoadingText(null);
        setPlayingText(trimmed);
        audio.onended = () => setPlayingText((current) => (current === trimmed ? null : current));
        audio.onerror = () => setPlayingText(null);
        await playAudioElement(audio);
      } catch {
        if (requestRef.current !== requestId) return;
        setLoadingText(null);
        speakWithBrowser(speakableSpanish(trimmed), rate);
      }
    },
    [],
  );

  return { speak, stop, loadingText, playingText };
}
